# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lib.hydra_pb import asset_pb2 as asset__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in asset_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AssetServiceStub(object):
    """Asset management service.

    Provides methods to query registered assets and add new tokens on any
    initialized network. Every network has a native asset (e.g., BTC, ETH) and
    may support additional tokens (e.g., ERC-20 contracts).

    JSON-RPC namespace: `asset`
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAssets = channel.unary_unary(
                '/hydra_app.AssetService/GetAssets',
                request_serializer=asset__pb2.GetAssetsRequest.SerializeToString,
                response_deserializer=asset__pb2.GetAssetsResponse.FromString,
                _registered_method=True)
        self.GetAsset = channel.unary_unary(
                '/hydra_app.AssetService/GetAsset',
                request_serializer=asset__pb2.GetAssetRequest.SerializeToString,
                response_deserializer=asset__pb2.GetAssetResponse.FromString,
                _registered_method=True)
        self.GetNativeAsset = channel.unary_unary(
                '/hydra_app.AssetService/GetNativeAsset',
                request_serializer=asset__pb2.GetNativeAssetRequest.SerializeToString,
                response_deserializer=asset__pb2.GetAssetResponse.FromString,
                _registered_method=True)
        self.AddToken = channel.unary_unary(
                '/hydra_app.AssetService/AddToken',
                request_serializer=asset__pb2.AddTokenRequest.SerializeToString,
                response_deserializer=asset__pb2.AddTokenResponse.FromString,
                _registered_method=True)


class AssetServiceServicer(object):
    """Asset management service.

    Provides methods to query registered assets and add new tokens on any
    initialized network. Every network has a native asset (e.g., BTC, ETH) and
    may support additional tokens (e.g., ERC-20 contracts).

    JSON-RPC namespace: `asset`
    """

    def GetAssets(self, request, context):
        """Returns all registered assets (native + tokens) on the specified network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAsset(self, request, context):
        """Returns the details of a specific asset by its ID on the specified
        network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNativeAsset(self, request, context):
        """Returns the native asset of the specified network (e.g., BTC for Bitcoin,
        ETH for Ethereum).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToken(self, request, context):
        """Registers a new token on the specified network by its contract address
        or token ID. The token metadata (name, symbol, decimals) will be fetched
        from the blockchain.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAssets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssets,
                    request_deserializer=asset__pb2.GetAssetsRequest.FromString,
                    response_serializer=asset__pb2.GetAssetsResponse.SerializeToString,
            ),
            'GetAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAsset,
                    request_deserializer=asset__pb2.GetAssetRequest.FromString,
                    response_serializer=asset__pb2.GetAssetResponse.SerializeToString,
            ),
            'GetNativeAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNativeAsset,
                    request_deserializer=asset__pb2.GetNativeAssetRequest.FromString,
                    response_serializer=asset__pb2.GetAssetResponse.SerializeToString,
            ),
            'AddToken': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToken,
                    request_deserializer=asset__pb2.AddTokenRequest.FromString,
                    response_serializer=asset__pb2.AddTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hydra_app.AssetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hydra_app.AssetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AssetService(object):
    """Asset management service.

    Provides methods to query registered assets and add new tokens on any
    initialized network. Every network has a native asset (e.g., BTC, ETH) and
    may support additional tokens (e.g., ERC-20 contracts).

    JSON-RPC namespace: `asset`
    """

    @staticmethod
    def GetAssets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.AssetService/GetAssets',
            asset__pb2.GetAssetsRequest.SerializeToString,
            asset__pb2.GetAssetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.AssetService/GetAsset',
            asset__pb2.GetAssetRequest.SerializeToString,
            asset__pb2.GetAssetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNativeAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.AssetService/GetNativeAsset',
            asset__pb2.GetNativeAssetRequest.SerializeToString,
            asset__pb2.GetAssetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.AssetService/AddToken',
            asset__pb2.AddTokenRequest.SerializeToString,
            asset__pb2.AddTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
