# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: asset.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'asset.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lib.hydra_pb import primitives_pb2 as primitives__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61sset.proto\x12\thydra_app\x1a\x10primitives.proto\"7\n\x10GetAssetsRequest\x12#\n\x07network\x18\x01 \x01(\x0b\x32\x12.hydra_app.Network\"5\n\x11GetAssetsResponse\x12 \n\x06\x61ssets\x18\x01 \x03(\x0b\x32\x10.hydra_app.Asset\"H\n\x0fGetAssetRequest\x12#\n\x07network\x18\x01 \x01(\x0b\x32\x12.hydra_app.Network\x12\x10\n\x08\x61sset_id\x18\x02 \x01(\t\"3\n\x10GetAssetResponse\x12\x1f\n\x05\x61sset\x18\x01 \x01(\x0b\x32\x10.hydra_app.Asset\"<\n\x15GetNativeAssetRequest\x12#\n\x07network\x18\x01 \x01(\x0b\x32\x12.hydra_app.Network\"\x84\x01\n\x0f\x41\x64\x64TokenRequest\x12#\n\x07network\x18\x01 \x01(\x0b\x32\x12.hydra_app.Network\x12\x10\n\x08token_id\x18\x02 \x01(\t\x12\x13\n\x06symbol\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04name\x18\x04 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_symbolB\x07\n\x05_name\"3\n\x10\x41\x64\x64TokenResponse\x12\x1f\n\x05\x61sset\x18\x01 \x01(\x0b\x32\x10.hydra_app.Asset2\xb9\x02\n\x0c\x41ssetService\x12H\n\tGetAssets\x12\x1b.hydra_app.GetAssetsRequest\x1a\x1c.hydra_app.GetAssetsResponse\"\x00\x12\x45\n\x08GetAsset\x12\x1a.hydra_app.GetAssetRequest\x1a\x1b.hydra_app.GetAssetResponse\"\x00\x12Q\n\x0eGetNativeAsset\x12 .hydra_app.GetNativeAssetRequest\x1a\x1b.hydra_app.GetAssetResponse\"\x00\x12\x45\n\x08\x41\x64\x64Token\x12\x1a.hydra_app.AddTokenRequest\x1a\x1b.hydra_app.AddTokenResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asset_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETASSETSREQUEST']._serialized_start=44
  _globals['_GETASSETSREQUEST']._serialized_end=99
  _globals['_GETASSETSRESPONSE']._serialized_start=101
  _globals['_GETASSETSRESPONSE']._serialized_end=154
  _globals['_GETASSETREQUEST']._serialized_start=156
  _globals['_GETASSETREQUEST']._serialized_end=228
  _globals['_GETASSETRESPONSE']._serialized_start=230
  _globals['_GETASSETRESPONSE']._serialized_end=281
  _globals['_GETNATIVEASSETREQUEST']._serialized_start=283
  _globals['_GETNATIVEASSETREQUEST']._serialized_end=343
  _globals['_ADDTOKENREQUEST']._serialized_start=346
  _globals['_ADDTOKENREQUEST']._serialized_end=478
  _globals['_ADDTOKENRESPONSE']._serialized_start=480
  _globals['_ADDTOKENRESPONSE']._serialized_end=531
  _globals['_ASSETSERVICE']._serialized_start=534
  _globals['_ASSETSERVICE']._serialized_end=847
# @@protoc_insertion_point(module_scope)
