# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lib.hydra_pb import blockchain_pb2 as blockchain__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in blockchain_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BlockchainServiceStub(object):
    """Blockchain query service.

    Provides read-only methods to query on-chain data such as block numbers,
    block headers, fee estimates, and token allowances. These are useful for
    building transactions and monitoring network state.

    JSON-RPC namespace: `blockchain`
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBlockNumber = channel.unary_unary(
                '/hydra_app.BlockchainService/GetBlockNumber',
                request_serializer=blockchain__pb2.GetBlockNumberRequest.SerializeToString,
                response_deserializer=blockchain__pb2.GetBlockNumberResponse.FromString,
                _registered_method=True)
        self.GetBlockHeader = channel.unary_unary(
                '/hydra_app.BlockchainService/GetBlockHeader',
                request_serializer=blockchain__pb2.GetBlockHeaderRequest.SerializeToString,
                response_deserializer=blockchain__pb2.GetBlockHeaderResponse.FromString,
                _registered_method=True)
        self.GetTransactionById = channel.unary_unary(
                '/hydra_app.BlockchainService/GetTransactionById',
                request_serializer=blockchain__pb2.GetTransactionByIdRequest.SerializeToString,
                response_deserializer=blockchain__pb2.GetTransactionByIdResponse.FromString,
                _registered_method=True)
        self.GetFeeEstimates = channel.unary_unary(
                '/hydra_app.BlockchainService/GetFeeEstimates',
                request_serializer=blockchain__pb2.GetFeeEstimatesRequest.SerializeToString,
                response_deserializer=blockchain__pb2.GetFeeEstimatesResponse.FromString,
                _registered_method=True)
        self.BroadcastRawTransaction = channel.unary_unary(
                '/hydra_app.BlockchainService/BroadcastRawTransaction',
                request_serializer=blockchain__pb2.BroadcastRawTransactionRequest.SerializeToString,
                response_deserializer=blockchain__pb2.BroadcastRawTransactionResponse.FromString,
                _registered_method=True)
        self.GetAddressBalance = channel.unary_unary(
                '/hydra_app.BlockchainService/GetAddressBalance',
                request_serializer=blockchain__pb2.GetAddressBalanceRequest.SerializeToString,
                response_deserializer=blockchain__pb2.GetAddressBalanceResponse.FromString,
                _registered_method=True)
        self.GetTokenBalance = channel.unary_unary(
                '/hydra_app.BlockchainService/GetTokenBalance',
                request_serializer=blockchain__pb2.GetTokenBalanceRequest.SerializeToString,
                response_deserializer=blockchain__pb2.GetTokenBalanceResponse.FromString,
                _registered_method=True)
        self.GetTokenAllowance = channel.unary_unary(
                '/hydra_app.BlockchainService/GetTokenAllowance',
                request_serializer=blockchain__pb2.GetTokenAllowanceRequest.SerializeToString,
                response_deserializer=blockchain__pb2.GetTokenAllowanceResponse.FromString,
                _registered_method=True)
        self.GetTokenPermitTerms = channel.unary_unary(
                '/hydra_app.BlockchainService/GetTokenPermitTerms',
                request_serializer=blockchain__pb2.GetTokenPermitTermsRequest.SerializeToString,
                response_deserializer=blockchain__pb2.GetTokenPermitTermsResponse.FromString,
                _registered_method=True)


class BlockchainServiceServicer(object):
    """Blockchain query service.

    Provides read-only methods to query on-chain data such as block numbers,
    block headers, fee estimates, and token allowances. These are useful for
    building transactions and monitoring network state.

    JSON-RPC namespace: `blockchain`
    """

    def GetBlockNumber(self, request, context):
        """Returns the latest block number (height) on the specified network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlockHeader(self, request, context):
        """Returns the block header for a specific block height on the specified
        network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionById(self, request, context):
        """Returns the details of a specific on-chain transaction by its ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFeeEstimates(self, request, context):
        """Returns fee estimates at low, medium, and high priority levels for the
        specified network. Use these to set appropriate fee rates when creating
        transactions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BroadcastRawTransaction(self, request, context):
        """Broadcasts a fully signed raw transaction to the specified network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAddressBalance(self, request, context):
        """Returns the native asset balance for an arbitrary address.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTokenBalance(self, request, context):
        """Returns the token balance for the given token and address.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTokenAllowance(self, request, context):
        """Returns the current token allowance granted by an owner to a spender on
        the specified network. Only applicable to EVM networks with ERC-20/721/1155
        tokens.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTokenPermitTerms(self, request, context):
        """Returns what a token discloses before an owner signs a permit for it —
        the terms a `TokenPermit` carries — or nothing when the token offers no
        signature-authorised allowance to that owner. Reading the terms is how
        a caller learns whether a permit is available at all.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlockchainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBlockNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlockNumber,
                    request_deserializer=blockchain__pb2.GetBlockNumberRequest.FromString,
                    response_serializer=blockchain__pb2.GetBlockNumberResponse.SerializeToString,
            ),
            'GetBlockHeader': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlockHeader,
                    request_deserializer=blockchain__pb2.GetBlockHeaderRequest.FromString,
                    response_serializer=blockchain__pb2.GetBlockHeaderResponse.SerializeToString,
            ),
            'GetTransactionById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionById,
                    request_deserializer=blockchain__pb2.GetTransactionByIdRequest.FromString,
                    response_serializer=blockchain__pb2.GetTransactionByIdResponse.SerializeToString,
            ),
            'GetFeeEstimates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeeEstimates,
                    request_deserializer=blockchain__pb2.GetFeeEstimatesRequest.FromString,
                    response_serializer=blockchain__pb2.GetFeeEstimatesResponse.SerializeToString,
            ),
            'BroadcastRawTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastRawTransaction,
                    request_deserializer=blockchain__pb2.BroadcastRawTransactionRequest.FromString,
                    response_serializer=blockchain__pb2.BroadcastRawTransactionResponse.SerializeToString,
            ),
            'GetAddressBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAddressBalance,
                    request_deserializer=blockchain__pb2.GetAddressBalanceRequest.FromString,
                    response_serializer=blockchain__pb2.GetAddressBalanceResponse.SerializeToString,
            ),
            'GetTokenBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTokenBalance,
                    request_deserializer=blockchain__pb2.GetTokenBalanceRequest.FromString,
                    response_serializer=blockchain__pb2.GetTokenBalanceResponse.SerializeToString,
            ),
            'GetTokenAllowance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTokenAllowance,
                    request_deserializer=blockchain__pb2.GetTokenAllowanceRequest.FromString,
                    response_serializer=blockchain__pb2.GetTokenAllowanceResponse.SerializeToString,
            ),
            'GetTokenPermitTerms': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTokenPermitTerms,
                    request_deserializer=blockchain__pb2.GetTokenPermitTermsRequest.FromString,
                    response_serializer=blockchain__pb2.GetTokenPermitTermsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hydra_app.BlockchainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hydra_app.BlockchainService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BlockchainService(object):
    """Blockchain query service.

    Provides read-only methods to query on-chain data such as block numbers,
    block headers, fee estimates, and token allowances. These are useful for
    building transactions and monitoring network state.

    JSON-RPC namespace: `blockchain`
    """

    @staticmethod
    def GetBlockNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.BlockchainService/GetBlockNumber',
            blockchain__pb2.GetBlockNumberRequest.SerializeToString,
            blockchain__pb2.GetBlockNumberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBlockHeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.BlockchainService/GetBlockHeader',
            blockchain__pb2.GetBlockHeaderRequest.SerializeToString,
            blockchain__pb2.GetBlockHeaderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransactionById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.BlockchainService/GetTransactionById',
            blockchain__pb2.GetTransactionByIdRequest.SerializeToString,
            blockchain__pb2.GetTransactionByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFeeEstimates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.BlockchainService/GetFeeEstimates',
            blockchain__pb2.GetFeeEstimatesRequest.SerializeToString,
            blockchain__pb2.GetFeeEstimatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BroadcastRawTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.BlockchainService/BroadcastRawTransaction',
            blockchain__pb2.BroadcastRawTransactionRequest.SerializeToString,
            blockchain__pb2.BroadcastRawTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAddressBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.BlockchainService/GetAddressBalance',
            blockchain__pb2.GetAddressBalanceRequest.SerializeToString,
            blockchain__pb2.GetAddressBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTokenBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.BlockchainService/GetTokenBalance',
            blockchain__pb2.GetTokenBalanceRequest.SerializeToString,
            blockchain__pb2.GetTokenBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTokenAllowance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.BlockchainService/GetTokenAllowance',
            blockchain__pb2.GetTokenAllowanceRequest.SerializeToString,
            blockchain__pb2.GetTokenAllowanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTokenPermitTerms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.BlockchainService/GetTokenPermitTerms',
            blockchain__pb2.GetTokenPermitTermsRequest.SerializeToString,
            blockchain__pb2.GetTokenPermitTermsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
