# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lib.hydra_pb import client_pb2 as client__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in client_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientServiceStub(object):
    """On-chain transaction service.

    Provides methods to create, sign, and broadcast on-chain transactions
    including native asset transfers, token transfers, fee bumping, and token
    allowance management.

    JSON-RPC namespace: `client`
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSendTransaction = channel.unary_unary(
                '/hydra_app.ClientService/CreateSendTransaction',
                request_serializer=client__pb2.CreateSendTransactionRequest.SerializeToString,
                response_deserializer=client__pb2.CreateSendTransactionResponse.FromString,
                _registered_method=True)
        self.GetBumpEligibility = channel.unary_unary(
                '/hydra_app.ClientService/GetBumpEligibility',
                request_serializer=client__pb2.GetBumpEligibilityRequest.SerializeToString,
                response_deserializer=client__pb2.GetBumpEligibilityResponse.FromString,
                _registered_method=True)
        self.CreateBumpTransaction = channel.unary_unary(
                '/hydra_app.ClientService/CreateBumpTransaction',
                request_serializer=client__pb2.CreateBumpTransactionRequest.SerializeToString,
                response_deserializer=client__pb2.CreateBumpTransactionResponse.FromString,
                _registered_method=True)
        self.CreateTokenSendTransaction = channel.unary_unary(
                '/hydra_app.ClientService/CreateTokenSendTransaction',
                request_serializer=client__pb2.CreateTokenSendTransactionRequest.SerializeToString,
                response_deserializer=client__pb2.CreateTokenSendTransactionResponse.FromString,
                _registered_method=True)
        self.CreateSetTokenAllowanceTransaction = channel.unary_unary(
                '/hydra_app.ClientService/CreateSetTokenAllowanceTransaction',
                request_serializer=client__pb2.CreateSetTokenAllowanceTransactionRequest.SerializeToString,
                response_deserializer=client__pb2.CreateSetTokenAllowanceTransactionResponse.FromString,
                _registered_method=True)
        self.FinalizeAndBroadcastTransaction = channel.unary_unary(
                '/hydra_app.ClientService/FinalizeAndBroadcastTransaction',
                request_serializer=client__pb2.FinalizeAndBroadcastTransactionRequest.SerializeToString,
                response_deserializer=client__pb2.FinalizeAndBroadcastTransactionResponse.FromString,
                _registered_method=True)
        self.SendTransaction = channel.unary_unary(
                '/hydra_app.ClientService/SendTransaction',
                request_serializer=client__pb2.SendTransactionRequest.SerializeToString,
                response_deserializer=client__pb2.SendTransactionResponse.FromString,
                _registered_method=True)
        self.BumpTransaction = channel.unary_unary(
                '/hydra_app.ClientService/BumpTransaction',
                request_serializer=client__pb2.BumpTransactionRequest.SerializeToString,
                response_deserializer=client__pb2.BumpTransactionResponse.FromString,
                _registered_method=True)
        self.SendTokenTransaction = channel.unary_unary(
                '/hydra_app.ClientService/SendTokenTransaction',
                request_serializer=client__pb2.SendTokenTransactionRequest.SerializeToString,
                response_deserializer=client__pb2.SendTokenTransactionResponse.FromString,
                _registered_method=True)
        self.SetTokenAllowance = channel.unary_unary(
                '/hydra_app.ClientService/SetTokenAllowance',
                request_serializer=client__pb2.SetTokenAllowanceRequest.SerializeToString,
                response_deserializer=client__pb2.SetTokenAllowanceResponse.FromString,
                _registered_method=True)
        self.CreateTokenPermitTransaction = channel.unary_unary(
                '/hydra_app.ClientService/CreateTokenPermitTransaction',
                request_serializer=client__pb2.CreateTokenPermitTransactionRequest.SerializeToString,
                response_deserializer=client__pb2.CreateTokenPermitTransactionResponse.FromString,
                _registered_method=True)
        self.EstimateTokenPermitFee = channel.unary_unary(
                '/hydra_app.ClientService/EstimateTokenPermitFee',
                request_serializer=client__pb2.EstimateTokenPermitFeeRequest.SerializeToString,
                response_deserializer=client__pb2.EstimateTokenPermitFeeResponse.FromString,
                _registered_method=True)
        self.SubmitTokenPermit = channel.unary_unary(
                '/hydra_app.ClientService/SubmitTokenPermit',
                request_serializer=client__pb2.SubmitTokenPermitRequest.SerializeToString,
                response_deserializer=client__pb2.SubmitTokenPermitResponse.FromString,
                _registered_method=True)


class ClientServiceServicer(object):
    """On-chain transaction service.

    Provides methods to create, sign, and broadcast on-chain transactions
    including native asset transfers, token transfers, fee bumping, and token
    allowance management.

    JSON-RPC namespace: `client`
    """

    def CreateSendTransaction(self, request, context):
        """Creates an unsigned native asset send transaction on the specified
        network.

        Returns a generic TransactionRequest that can be inspected, signed via
        `signer.SignTransaction`, and then finalized and broadcast via
        `FinalizeAndBroadcastTransaction`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBumpEligibility(self, request, context):
        """Reports whether an unconfirmed transaction's fee can be raised, by which
        mechanism, and from what floor.

        Answered from state the node already holds, so a caller can decide
        whether to offer fee bumping — and on what terms — before attempting it.
        The floor is not a ceiling: it does not promise that any particular rate
        above it is reachable.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBumpTransaction(self, request, context):
        """Creates an unsigned fee-bump transaction request for an existing
        unconfirmed transaction.

        Returns a generic TransactionRequest that can be signed and broadcast
        separately. Fails when the transaction cannot be bumped; call
        GetBumpEligibility to find out in advance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTokenSendTransaction(self, request, context):
        """Creates an unsigned token send transaction on the specified network.

        Returns a generic TransactionRequest that can be signed and broadcast
        separately. For native asset transfers, use CreateSendTransaction.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSetTokenAllowanceTransaction(self, request, context):
        """Creates an unsigned token allowance approval transaction on the
        specified network.

        Returns a generic TransactionRequest that can be signed and broadcast
        separately.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeAndBroadcastTransaction(self, request, context):
        """Finalizes and broadcasts a signed transaction request to the network.

        Accepts a SignedTransactionRequest (as returned by
        `signer.SignTransaction`) and returns the resulting transaction ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTransaction(self, request, context):
        """Sends a native asset transaction on the specified network.

        Use this to transfer the network's native asset (e.g., BTC, ETH) to
        another address. For token transfers, use SendTokenTransaction instead.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BumpTransaction(self, request, context):
        """Bumps the fee of an existing unconfirmed transaction.

        This creates a replacement transaction (RBF on Bitcoin, speed-up on EVM)
        with a higher fee to accelerate confirmation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTokenTransaction(self, request, context):
        """Sends a token transfer transaction on the specified network.

        Use this to transfer ERC-20 or other tokens. For native asset transfers,
        use SendTransaction instead.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTokenAllowance(self, request, context):
        """Sets the token spending allowance on the specified network.

        Approves a spender address to transfer up to a specified amount of tokens
        on behalf of the wallet owner. Supports ERC-20, ERC-721, and ERC-1155.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTokenPermitTransaction(self, request, context):
        """Creates an unsigned transaction submitting a signed token permit on the
        specified network.

        The permit's owner authorised the allowance off-chain; this wallet sends
        the transaction that sets it and pays the fee. Returns a generic
        TransactionRequest that can be signed and broadcast separately.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateTokenPermitFee(self, request, context):
        """Estimates what submitting a token permit would cost this wallet.

        The permit does not exist yet — its owner signs it once the price is
        known — so this prices the submission against the owner's live state on
        the token without a signature. No transaction is created or broadcast.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTokenPermit(self, request, context):
        """Submits a signed token permit on the specified network.

        Creates, signs and broadcasts the transaction that sets the allowance
        the permit's owner authorised. Returns the transaction ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSendTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSendTransaction,
                    request_deserializer=client__pb2.CreateSendTransactionRequest.FromString,
                    response_serializer=client__pb2.CreateSendTransactionResponse.SerializeToString,
            ),
            'GetBumpEligibility': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBumpEligibility,
                    request_deserializer=client__pb2.GetBumpEligibilityRequest.FromString,
                    response_serializer=client__pb2.GetBumpEligibilityResponse.SerializeToString,
            ),
            'CreateBumpTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBumpTransaction,
                    request_deserializer=client__pb2.CreateBumpTransactionRequest.FromString,
                    response_serializer=client__pb2.CreateBumpTransactionResponse.SerializeToString,
            ),
            'CreateTokenSendTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTokenSendTransaction,
                    request_deserializer=client__pb2.CreateTokenSendTransactionRequest.FromString,
                    response_serializer=client__pb2.CreateTokenSendTransactionResponse.SerializeToString,
            ),
            'CreateSetTokenAllowanceTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSetTokenAllowanceTransaction,
                    request_deserializer=client__pb2.CreateSetTokenAllowanceTransactionRequest.FromString,
                    response_serializer=client__pb2.CreateSetTokenAllowanceTransactionResponse.SerializeToString,
            ),
            'FinalizeAndBroadcastTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeAndBroadcastTransaction,
                    request_deserializer=client__pb2.FinalizeAndBroadcastTransactionRequest.FromString,
                    response_serializer=client__pb2.FinalizeAndBroadcastTransactionResponse.SerializeToString,
            ),
            'SendTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTransaction,
                    request_deserializer=client__pb2.SendTransactionRequest.FromString,
                    response_serializer=client__pb2.SendTransactionResponse.SerializeToString,
            ),
            'BumpTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.BumpTransaction,
                    request_deserializer=client__pb2.BumpTransactionRequest.FromString,
                    response_serializer=client__pb2.BumpTransactionResponse.SerializeToString,
            ),
            'SendTokenTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTokenTransaction,
                    request_deserializer=client__pb2.SendTokenTransactionRequest.FromString,
                    response_serializer=client__pb2.SendTokenTransactionResponse.SerializeToString,
            ),
            'SetTokenAllowance': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTokenAllowance,
                    request_deserializer=client__pb2.SetTokenAllowanceRequest.FromString,
                    response_serializer=client__pb2.SetTokenAllowanceResponse.SerializeToString,
            ),
            'CreateTokenPermitTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTokenPermitTransaction,
                    request_deserializer=client__pb2.CreateTokenPermitTransactionRequest.FromString,
                    response_serializer=client__pb2.CreateTokenPermitTransactionResponse.SerializeToString,
            ),
            'EstimateTokenPermitFee': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateTokenPermitFee,
                    request_deserializer=client__pb2.EstimateTokenPermitFeeRequest.FromString,
                    response_serializer=client__pb2.EstimateTokenPermitFeeResponse.SerializeToString,
            ),
            'SubmitTokenPermit': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTokenPermit,
                    request_deserializer=client__pb2.SubmitTokenPermitRequest.FromString,
                    response_serializer=client__pb2.SubmitTokenPermitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hydra_app.ClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hydra_app.ClientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientService(object):
    """On-chain transaction service.

    Provides methods to create, sign, and broadcast on-chain transactions
    including native asset transfers, token transfers, fee bumping, and token
    allowance management.

    JSON-RPC namespace: `client`
    """

    @staticmethod
    def CreateSendTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.ClientService/CreateSendTransaction',
            client__pb2.CreateSendTransactionRequest.SerializeToString,
            client__pb2.CreateSendTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBumpEligibility(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.ClientService/GetBumpEligibility',
            client__pb2.GetBumpEligibilityRequest.SerializeToString,
            client__pb2.GetBumpEligibilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBumpTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.ClientService/CreateBumpTransaction',
            client__pb2.CreateBumpTransactionRequest.SerializeToString,
            client__pb2.CreateBumpTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTokenSendTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.ClientService/CreateTokenSendTransaction',
            client__pb2.CreateTokenSendTransactionRequest.SerializeToString,
            client__pb2.CreateTokenSendTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSetTokenAllowanceTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.ClientService/CreateSetTokenAllowanceTransaction',
            client__pb2.CreateSetTokenAllowanceTransactionRequest.SerializeToString,
            client__pb2.CreateSetTokenAllowanceTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinalizeAndBroadcastTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.ClientService/FinalizeAndBroadcastTransaction',
            client__pb2.FinalizeAndBroadcastTransactionRequest.SerializeToString,
            client__pb2.FinalizeAndBroadcastTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.ClientService/SendTransaction',
            client__pb2.SendTransactionRequest.SerializeToString,
            client__pb2.SendTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BumpTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.ClientService/BumpTransaction',
            client__pb2.BumpTransactionRequest.SerializeToString,
            client__pb2.BumpTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTokenTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.ClientService/SendTokenTransaction',
            client__pb2.SendTokenTransactionRequest.SerializeToString,
            client__pb2.SendTokenTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTokenAllowance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.ClientService/SetTokenAllowance',
            client__pb2.SetTokenAllowanceRequest.SerializeToString,
            client__pb2.SetTokenAllowanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTokenPermitTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.ClientService/CreateTokenPermitTransaction',
            client__pb2.CreateTokenPermitTransactionRequest.SerializeToString,
            client__pb2.CreateTokenPermitTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateTokenPermitFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.ClientService/EstimateTokenPermitFee',
            client__pb2.EstimateTokenPermitFeeRequest.SerializeToString,
            client__pb2.EstimateTokenPermitFeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTokenPermit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.ClientService/SubmitTokenPermit',
            client__pb2.SubmitTokenPermitRequest.SerializeToString,
            client__pb2.SubmitTokenPermitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
