# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fee.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fee.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lib.hydra_pb import primitives_pb2 as primitives__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tfee.proto\x12\thydra_app\x1a\x10primitives.proto\"p\n\x07\x46\x65\x65Rate\x12/\n\x10max_fee_per_unit\x18\x01 \x01(\x0b\x32\x15.hydra_app.U256String\x12\x34\n\x15priority_fee_per_unit\x18\x02 \x01(\x0b\x32\x15.hydra_app.U256String\"\x99\x01\n\x08\x43hainFee\x12\x30\n\x11\x62\x61se_fee_per_unit\x18\x01 \x01(\x0b\x32\x15.hydra_app.U256String\x12$\n\x08\x66\x65\x65_rate\x18\x02 \x01(\x0b\x32\x12.hydra_app.FeeRate\x12\x35\n\x16\x65\x66\x66\x65\x63tive_fee_per_unit\x18\x03 \x01(\x0b\x32\x15.hydra_app.U256String\"w\n\x0b\x46\x65\x65\x45stimate\x12 \n\x03low\x18\x01 \x01(\x0b\x32\x13.hydra_app.ChainFee\x12#\n\x06medium\x18\x02 \x01(\x0b\x32\x13.hydra_app.ChainFee\x12!\n\x04high\x18\x03 \x01(\x0b\x32\x13.hydra_app.ChainFee\"\x94\x02\n\tFeeOption\x12\'\n\x03low\x18\x01 \x01(\x0b\x32\x18.hydra_app.FeeOption.LowH\x00\x12-\n\x06medium\x18\x02 \x01(\x0b\x32\x1b.hydra_app.FeeOption.MediumH\x00\x12)\n\x04high\x18\x03 \x01(\x0b\x32\x19.hydra_app.FeeOption.HighH\x00\x12-\n\x06\x63ustom\x18\x04 \x01(\x0b\x32\x1b.hydra_app.FeeOption.CustomH\x00\x1a\x05\n\x03Low\x1a\x08\n\x06Medium\x1a\x06\n\x04High\x1a.\n\x06\x43ustom\x12$\n\x08\x66\x65\x65_rate\x18\x01 \x01(\x0b\x32\x12.hydra_app.FeeRateB\x0c\n\nfee_optionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fee_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FEERATE']._serialized_start=42
  _globals['_FEERATE']._serialized_end=154
  _globals['_CHAINFEE']._serialized_start=157
  _globals['_CHAINFEE']._serialized_end=310
  _globals['_FEEESTIMATE']._serialized_start=312
  _globals['_FEEESTIMATE']._serialized_end=431
  _globals['_FEEOPTION']._serialized_start=434
  _globals['_FEEOPTION']._serialized_end=710
  _globals['_FEEOPTION_LOW']._serialized_start=625
  _globals['_FEEOPTION_LOW']._serialized_end=630
  _globals['_FEEOPTION_MEDIUM']._serialized_start=632
  _globals['_FEEOPTION_MEDIUM']._serialized_end=640
  _globals['_FEEOPTION_HIGH']._serialized_start=642
  _globals['_FEEOPTION_HIGH']._serialized_end=648
  _globals['_FEEOPTION_CUSTOM']._serialized_start=650
  _globals['_FEEOPTION_CUSTOM']._serialized_end=696
# @@protoc_insertion_point(module_scope)
