# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lib.hydra_pb import htlc_pb2 as htlc__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in htlc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HtlcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateHtlc = channel.unary_unary(
                '/hydra_app.HtlcService/CreateHtlc',
                request_serializer=htlc__pb2.CreateHtlcRequest.SerializeToString,
                response_deserializer=htlc__pb2.CreateHtlcResponse.FromString,
                _registered_method=True)
        self.BatchCreateHtlcs = channel.unary_unary(
                '/hydra_app.HtlcService/BatchCreateHtlcs',
                request_serializer=htlc__pb2.BatchCreateHtlcsRequest.SerializeToString,
                response_deserializer=htlc__pb2.BatchCreateHtlcsResponse.FromString,
                _registered_method=True)
        self.ClaimHtlc = channel.unary_unary(
                '/hydra_app.HtlcService/ClaimHtlc',
                request_serializer=htlc__pb2.ClaimHtlcRequest.SerializeToString,
                response_deserializer=htlc__pb2.ClaimHtlcResponse.FromString,
                _registered_method=True)
        self.RefundHtlc = channel.unary_unary(
                '/hydra_app.HtlcService/RefundHtlc',
                request_serializer=htlc__pb2.RefundHtlcRequest.SerializeToString,
                response_deserializer=htlc__pb2.RefundHtlcResponse.FromString,
                _registered_method=True)
        self.CreateHtlcLockTx = channel.unary_unary(
                '/hydra_app.HtlcService/CreateHtlcLockTx',
                request_serializer=htlc__pb2.CreateHtlcLockTxRequest.SerializeToString,
                response_deserializer=htlc__pb2.HtlcTransactionRequest.FromString,
                _registered_method=True)
        self.CreateHtlcClaimTx = channel.unary_unary(
                '/hydra_app.HtlcService/CreateHtlcClaimTx',
                request_serializer=htlc__pb2.CreateHtlcClaimTxRequest.SerializeToString,
                response_deserializer=htlc__pb2.HtlcTransactionRequest.FromString,
                _registered_method=True)
        self.CreateHtlcRefundTx = channel.unary_unary(
                '/hydra_app.HtlcService/CreateHtlcRefundTx',
                request_serializer=htlc__pb2.CreateHtlcRefundTxRequest.SerializeToString,
                response_deserializer=htlc__pb2.HtlcTransactionRequest.FromString,
                _registered_method=True)
        self.VerifyHtlc = channel.unary_unary(
                '/hydra_app.HtlcService/VerifyHtlc',
                request_serializer=htlc__pb2.VerifyHtlcRequest.SerializeToString,
                response_deserializer=htlc__pb2.VerifyHtlcResponse.FromString,
                _registered_method=True)
        self.GetChainHtlc = channel.unary_unary(
                '/hydra_app.HtlcService/GetChainHtlc',
                request_serializer=htlc__pb2.GetChainHtlcRequest.SerializeToString,
                response_deserializer=htlc__pb2.GetChainHtlcResponse.FromString,
                _registered_method=True)
        self.BatchVerifyHtlcs = channel.unary_unary(
                '/hydra_app.HtlcService/BatchVerifyHtlcs',
                request_serializer=htlc__pb2.BatchVerifyHtlcsRequest.SerializeToString,
                response_deserializer=htlc__pb2.BatchVerifyHtlcsResponse.FromString,
                _registered_method=True)
        self.GetHtlcPubkey = channel.unary_unary(
                '/hydra_app.HtlcService/GetHtlcPubkey',
                request_serializer=htlc__pb2.GetHtlcPubkeyRequest.SerializeToString,
                response_deserializer=htlc__pb2.GetHtlcPubkeyResponse.FromString,
                _registered_method=True)
        self.GetUniqueHtlcPubkey = channel.unary_unary(
                '/hydra_app.HtlcService/GetUniqueHtlcPubkey',
                request_serializer=htlc__pb2.GetHtlcPubkeyRequest.SerializeToString,
                response_deserializer=htlc__pb2.GetHtlcPubkeyResponse.FromString,
                _registered_method=True)
        self.WatchHtlc = channel.unary_unary(
                '/hydra_app.HtlcService/WatchHtlc',
                request_serializer=htlc__pb2.WatchHtlcRequest.SerializeToString,
                response_deserializer=htlc__pb2.WatchHtlcResponse.FromString,
                _registered_method=True)
        self.UnwatchHtlc = channel.unary_unary(
                '/hydra_app.HtlcService/UnwatchHtlc',
                request_serializer=htlc__pb2.UnwatchHtlcRequest.SerializeToString,
                response_deserializer=htlc__pb2.UnwatchHtlcResponse.FromString,
                _registered_method=True)
        self.CreateHtlcSettlementTx = channel.unary_unary(
                '/hydra_app.HtlcService/CreateHtlcSettlementTx',
                request_serializer=htlc__pb2.CreateHtlcSettlementTxRequest.SerializeToString,
                response_deserializer=htlc__pb2.CreateHtlcSettlementTxResponse.FromString,
                _registered_method=True)
        self.BroadcastHtlcSettlement = channel.unary_unary(
                '/hydra_app.HtlcService/BroadcastHtlcSettlement',
                request_serializer=htlc__pb2.BroadcastHtlcSettlementRequest.SerializeToString,
                response_deserializer=htlc__pb2.BroadcastHtlcSettlementResponse.FromString,
                _registered_method=True)
        self.DeriveHtlcAddress = channel.unary_unary(
                '/hydra_app.HtlcService/DeriveHtlcAddress',
                request_serializer=htlc__pb2.DeriveHtlcAddressRequest.SerializeToString,
                response_deserializer=htlc__pb2.DeriveHtlcAddressResponse.FromString,
                _registered_method=True)
        self.VerifyHtlcByLockTxid = channel.unary_unary(
                '/hydra_app.HtlcService/VerifyHtlcByLockTxid',
                request_serializer=htlc__pb2.VerifyHtlcByLockTxidRequest.SerializeToString,
                response_deserializer=htlc__pb2.VerifyHtlcByLockTxidResponse.FromString,
                _registered_method=True)


class HtlcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateHtlc(self, request, context):
        """Lock funds into a new onchain HTLC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchCreateHtlcs(self, request, context):
        """Lock funds into multiple HTLCs in a single transaction (where supported).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimHtlc(self, request, context):
        """Claim an HTLC by revealing the preimage.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefundHtlc(self, request, context):
        """Refund an expired HTLC back to the sender.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateHtlcLockTx(self, request, context):
        """Build an UNSIGNED HTLC lock transaction (calldata / PSBT) for an external
        party to sign and broadcast. Unlike CreateHtlc, the node does not sign,
        broadcast, or key the refund branch to itself — the caller owns signing and
        supplies `refund_address`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateHtlcClaimTx(self, request, context):
        """Build an UNSIGNED HTLC claim transaction for an external signer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateHtlcRefundTx(self, request, context):
        """Build an UNSIGNED HTLC refund transaction for an external signer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyHtlc(self, request, context):
        """Verify an onchain HTLC matches expected parameters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChainHtlc(self, request, context):
        """Read an HTLC's current state directly from the chain by its lock
        transaction — a raw read with no expectation checks and no record
        persistence (VerifyHtlc is the term-judging read). The response carries
        no HTLC when the chain cannot produce it: unknown lock transaction, or
        parameters the chain does not reveal (e.g. a Bitcoin HTLC that is unspent,
        or Taproot-spent with the unused leaf hidden).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchVerifyHtlcs(self, request, context):
        """Verify multiple HTLCs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHtlcPubkey(self, request, context):
        """Fetch the node's own HTLC public key on a network — the key its locks
        refund to on timeout, and the identity counterparties lock to.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUniqueHtlcPubkey(self, request, context):
        """Reserve a fresh, unique HTLC public key. On UTXO protocols each call
        returns a key never handed out before; account-based protocols return their
        single stable key.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchHtlc(self, request, context):
        """Watch an externally-locked HTLC the node did not create itself, so its
        lifecycle transitions arrive on the node event stream.  Fire-and-forget.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnwatchHtlc(self, request, context):
        """Stop observing an HTLC — abort and deregister its watcher. Idempotent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateHtlcSettlementTx(self, request, context):
        """Build an UNSIGNED HTLC settlement transaction spending an HTLC to a fixed
        output, for an external signer to pre-sign. Applies only to signature-gated
        (UTXO-model) protocols; account-model protocols settle permissionlessly and
        reject this with FAILED_PRECONDITION.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BroadcastHtlcSettlement(self, request, context):
        """Broadcast a user-pre-signed HTLC settlement transaction, injecting the swap
        secret (the preimage, for a hashlock claim) if the branch requires it.
        UTXO-model protocols only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeriveHtlcAddress(self, request, context):
        """The address the HTLC parameters commit to under the node's configured
        script kind — the address an external wallet pays to fund the HTLC.
        UTXO-model protocols only (account-model HTLCs have no fund-by-address
        form); rejected with FAILED_PRECONDITION otherwise.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyHtlcByLockTxid(self, request, context):
        """Locate the HTLC output inside the attested funding transaction, verify it
        against the expected parameters, seed the node's record, and return the
        full HTLC (carrying its chain-native id). The entry point for an
        externally-funded HTLC whose outpoint the funder cannot know in advance.
        UTXO-model protocols only; rejected with FAILED_PRECONDITION otherwise.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HtlcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateHtlc': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateHtlc,
                    request_deserializer=htlc__pb2.CreateHtlcRequest.FromString,
                    response_serializer=htlc__pb2.CreateHtlcResponse.SerializeToString,
            ),
            'BatchCreateHtlcs': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchCreateHtlcs,
                    request_deserializer=htlc__pb2.BatchCreateHtlcsRequest.FromString,
                    response_serializer=htlc__pb2.BatchCreateHtlcsResponse.SerializeToString,
            ),
            'ClaimHtlc': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimHtlc,
                    request_deserializer=htlc__pb2.ClaimHtlcRequest.FromString,
                    response_serializer=htlc__pb2.ClaimHtlcResponse.SerializeToString,
            ),
            'RefundHtlc': grpc.unary_unary_rpc_method_handler(
                    servicer.RefundHtlc,
                    request_deserializer=htlc__pb2.RefundHtlcRequest.FromString,
                    response_serializer=htlc__pb2.RefundHtlcResponse.SerializeToString,
            ),
            'CreateHtlcLockTx': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateHtlcLockTx,
                    request_deserializer=htlc__pb2.CreateHtlcLockTxRequest.FromString,
                    response_serializer=htlc__pb2.HtlcTransactionRequest.SerializeToString,
            ),
            'CreateHtlcClaimTx': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateHtlcClaimTx,
                    request_deserializer=htlc__pb2.CreateHtlcClaimTxRequest.FromString,
                    response_serializer=htlc__pb2.HtlcTransactionRequest.SerializeToString,
            ),
            'CreateHtlcRefundTx': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateHtlcRefundTx,
                    request_deserializer=htlc__pb2.CreateHtlcRefundTxRequest.FromString,
                    response_serializer=htlc__pb2.HtlcTransactionRequest.SerializeToString,
            ),
            'VerifyHtlc': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyHtlc,
                    request_deserializer=htlc__pb2.VerifyHtlcRequest.FromString,
                    response_serializer=htlc__pb2.VerifyHtlcResponse.SerializeToString,
            ),
            'GetChainHtlc': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChainHtlc,
                    request_deserializer=htlc__pb2.GetChainHtlcRequest.FromString,
                    response_serializer=htlc__pb2.GetChainHtlcResponse.SerializeToString,
            ),
            'BatchVerifyHtlcs': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchVerifyHtlcs,
                    request_deserializer=htlc__pb2.BatchVerifyHtlcsRequest.FromString,
                    response_serializer=htlc__pb2.BatchVerifyHtlcsResponse.SerializeToString,
            ),
            'GetHtlcPubkey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHtlcPubkey,
                    request_deserializer=htlc__pb2.GetHtlcPubkeyRequest.FromString,
                    response_serializer=htlc__pb2.GetHtlcPubkeyResponse.SerializeToString,
            ),
            'GetUniqueHtlcPubkey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUniqueHtlcPubkey,
                    request_deserializer=htlc__pb2.GetHtlcPubkeyRequest.FromString,
                    response_serializer=htlc__pb2.GetHtlcPubkeyResponse.SerializeToString,
            ),
            'WatchHtlc': grpc.unary_unary_rpc_method_handler(
                    servicer.WatchHtlc,
                    request_deserializer=htlc__pb2.WatchHtlcRequest.FromString,
                    response_serializer=htlc__pb2.WatchHtlcResponse.SerializeToString,
            ),
            'UnwatchHtlc': grpc.unary_unary_rpc_method_handler(
                    servicer.UnwatchHtlc,
                    request_deserializer=htlc__pb2.UnwatchHtlcRequest.FromString,
                    response_serializer=htlc__pb2.UnwatchHtlcResponse.SerializeToString,
            ),
            'CreateHtlcSettlementTx': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateHtlcSettlementTx,
                    request_deserializer=htlc__pb2.CreateHtlcSettlementTxRequest.FromString,
                    response_serializer=htlc__pb2.CreateHtlcSettlementTxResponse.SerializeToString,
            ),
            'BroadcastHtlcSettlement': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastHtlcSettlement,
                    request_deserializer=htlc__pb2.BroadcastHtlcSettlementRequest.FromString,
                    response_serializer=htlc__pb2.BroadcastHtlcSettlementResponse.SerializeToString,
            ),
            'DeriveHtlcAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.DeriveHtlcAddress,
                    request_deserializer=htlc__pb2.DeriveHtlcAddressRequest.FromString,
                    response_serializer=htlc__pb2.DeriveHtlcAddressResponse.SerializeToString,
            ),
            'VerifyHtlcByLockTxid': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyHtlcByLockTxid,
                    request_deserializer=htlc__pb2.VerifyHtlcByLockTxidRequest.FromString,
                    response_serializer=htlc__pb2.VerifyHtlcByLockTxidResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hydra_app.HtlcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hydra_app.HtlcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HtlcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateHtlc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.HtlcService/CreateHtlc',
            htlc__pb2.CreateHtlcRequest.SerializeToString,
            htlc__pb2.CreateHtlcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchCreateHtlcs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.HtlcService/BatchCreateHtlcs',
            htlc__pb2.BatchCreateHtlcsRequest.SerializeToString,
            htlc__pb2.BatchCreateHtlcsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimHtlc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.HtlcService/ClaimHtlc',
            htlc__pb2.ClaimHtlcRequest.SerializeToString,
            htlc__pb2.ClaimHtlcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefundHtlc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.HtlcService/RefundHtlc',
            htlc__pb2.RefundHtlcRequest.SerializeToString,
            htlc__pb2.RefundHtlcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateHtlcLockTx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.HtlcService/CreateHtlcLockTx',
            htlc__pb2.CreateHtlcLockTxRequest.SerializeToString,
            htlc__pb2.HtlcTransactionRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateHtlcClaimTx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.HtlcService/CreateHtlcClaimTx',
            htlc__pb2.CreateHtlcClaimTxRequest.SerializeToString,
            htlc__pb2.HtlcTransactionRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateHtlcRefundTx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.HtlcService/CreateHtlcRefundTx',
            htlc__pb2.CreateHtlcRefundTxRequest.SerializeToString,
            htlc__pb2.HtlcTransactionRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyHtlc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.HtlcService/VerifyHtlc',
            htlc__pb2.VerifyHtlcRequest.SerializeToString,
            htlc__pb2.VerifyHtlcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChainHtlc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.HtlcService/GetChainHtlc',
            htlc__pb2.GetChainHtlcRequest.SerializeToString,
            htlc__pb2.GetChainHtlcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchVerifyHtlcs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.HtlcService/BatchVerifyHtlcs',
            htlc__pb2.BatchVerifyHtlcsRequest.SerializeToString,
            htlc__pb2.BatchVerifyHtlcsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHtlcPubkey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.HtlcService/GetHtlcPubkey',
            htlc__pb2.GetHtlcPubkeyRequest.SerializeToString,
            htlc__pb2.GetHtlcPubkeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUniqueHtlcPubkey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.HtlcService/GetUniqueHtlcPubkey',
            htlc__pb2.GetHtlcPubkeyRequest.SerializeToString,
            htlc__pb2.GetHtlcPubkeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchHtlc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.HtlcService/WatchHtlc',
            htlc__pb2.WatchHtlcRequest.SerializeToString,
            htlc__pb2.WatchHtlcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnwatchHtlc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.HtlcService/UnwatchHtlc',
            htlc__pb2.UnwatchHtlcRequest.SerializeToString,
            htlc__pb2.UnwatchHtlcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateHtlcSettlementTx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.HtlcService/CreateHtlcSettlementTx',
            htlc__pb2.CreateHtlcSettlementTxRequest.SerializeToString,
            htlc__pb2.CreateHtlcSettlementTxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BroadcastHtlcSettlement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.HtlcService/BroadcastHtlcSettlement',
            htlc__pb2.BroadcastHtlcSettlementRequest.SerializeToString,
            htlc__pb2.BroadcastHtlcSettlementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeriveHtlcAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.HtlcService/DeriveHtlcAddress',
            htlc__pb2.DeriveHtlcAddressRequest.SerializeToString,
            htlc__pb2.DeriveHtlcAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyHtlcByLockTxid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.HtlcService/VerifyHtlcByLockTxid',
            htlc__pb2.VerifyHtlcByLockTxidRequest.SerializeToString,
            htlc__pb2.VerifyHtlcByLockTxidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
