# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lib.hydra_pb import liquidity_pb2 as liquidity__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in liquidity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LiquidityServiceStub(object):
    """Channel liquidity service.

    Exposes Hydra App's service-backed channel liquidity surface. Hydra App
    completes fee settlement and any required local confirmations internally
    before returning the final operation result.

    JSON-RPC namespace: `liquidity`
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLiquidityServiceInfo = channel.unary_unary(
                '/hydra_app.LiquidityService/GetLiquidityServiceInfo',
                request_serializer=liquidity__pb2.GetLiquidityServiceInfoRequest.SerializeToString,
                response_deserializer=liquidity__pb2.GetLiquidityServiceInfoResponse.FromString,
                _registered_method=True)
        self.GetLeaseableAssetInfo = channel.unary_unary(
                '/hydra_app.LiquidityService/GetLeaseableAssetInfo',
                request_serializer=liquidity__pb2.GetLeaseableAssetInfoRequest.SerializeToString,
                response_deserializer=liquidity__pb2.GetLeaseableAssetInfoResponse.FromString,
                _registered_method=True)
        self.GetLeases = channel.unary_unary(
                '/hydra_app.LiquidityService/GetLeases',
                request_serializer=liquidity__pb2.GetLeasesRequest.SerializeToString,
                response_deserializer=liquidity__pb2.GetLeasesResponse.FromString,
                _registered_method=True)
        self.GetLeaseExpiries = channel.unary_unary(
                '/hydra_app.LiquidityService/GetLeaseExpiries',
                request_serializer=liquidity__pb2.GetLeaseExpiriesRequest.SerializeToString,
                response_deserializer=liquidity__pb2.GetLeaseExpiriesResponse.FromString,
                _registered_method=True)
        self.GetFeePayments = channel.unary_unary(
                '/hydra_app.LiquidityService/GetFeePayments',
                request_serializer=liquidity__pb2.GetFeePaymentsRequest.SerializeToString,
                response_deserializer=liquidity__pb2.GetFeePaymentsResponse.FromString,
                _registered_method=True)
        self.RequestChannelLiquidity = channel.unary_unary(
                '/hydra_app.LiquidityService/RequestChannelLiquidity',
                request_serializer=liquidity__pb2.RequestChannelLiquidityRequest.SerializeToString,
                response_deserializer=liquidity__pb2.RequestChannelLiquidityResponse.FromString,
                _registered_method=True)
        self.EstimateRequestChannelLiquidityFee = channel.unary_unary(
                '/hydra_app.LiquidityService/EstimateRequestChannelLiquidityFee',
                request_serializer=liquidity__pb2.RequestChannelLiquidityRequest.SerializeToString,
                response_deserializer=liquidity__pb2.EstimateRequestFeeResponse.FromString,
                _registered_method=True)
        self.RequestChannelRelease = channel.unary_unary(
                '/hydra_app.LiquidityService/RequestChannelRelease',
                request_serializer=liquidity__pb2.RequestChannelReleaseRequest.SerializeToString,
                response_deserializer=liquidity__pb2.RequestChannelReleaseResponse.FromString,
                _registered_method=True)
        self.EstimateRequestChannelReleaseFee = channel.unary_unary(
                '/hydra_app.LiquidityService/EstimateRequestChannelReleaseFee',
                request_serializer=liquidity__pb2.RequestChannelReleaseRequest.SerializeToString,
                response_deserializer=liquidity__pb2.EstimateRequestFeeResponse.FromString,
                _registered_method=True)
        self.RequestChannelLeaseExtension = channel.unary_unary(
                '/hydra_app.LiquidityService/RequestChannelLeaseExtension',
                request_serializer=liquidity__pb2.RequestChannelLeaseExtensionRequest.SerializeToString,
                response_deserializer=liquidity__pb2.RequestChannelLeaseExtensionResponse.FromString,
                _registered_method=True)
        self.EstimateRequestChannelLeaseExtensionFee = channel.unary_unary(
                '/hydra_app.LiquidityService/EstimateRequestChannelLeaseExtensionFee',
                request_serializer=liquidity__pb2.RequestChannelLeaseExtensionRequest.SerializeToString,
                response_deserializer=liquidity__pb2.EstimateRequestFeeResponse.FromString,
                _registered_method=True)


class LiquidityServiceServicer(object):
    """Channel liquidity service.

    Exposes Hydra App's service-backed channel liquidity surface. Hydra App
    completes fee settlement and any required local confirmations internally
    before returning the final operation result.

    JSON-RPC namespace: `liquidity`
    """

    def GetLiquidityServiceInfo(self, request, context):
        """Read-only: server-wide capacity bounds, durations, asset configs, and
        the LP's per-network node public keys.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLeaseableAssetInfo(self, request, context):
        """Read-only: per-asset liquidity bounds + fee ratio for a single
        (network, asset) on the LP.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLeases(self, request, context):
        """Read-only: list the requesting client's active leases on a network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLeaseExpiries(self, request, context):
        """Read-only: lease expiry per (channel_id, asset_id) for a network.
        Local cache only — no network round-trip to the LP.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFeePayments(self, request, context):
        """Read-only: what this node has been billed on a network, newest first.

        The reconciliation surface for fees already paid. A request's own
        response reports the fee for that one request and nothing re-reads it
        afterwards, so this is where a ledger, an export or a tax report gets
        its rows — including for payments that expired, failed or were
        refunded, which no response ever returned.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestChannelLiquidity(self, request, context):
        """Ask the liquidity service to provision channel liquidity on the client's
        behalf.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateRequestChannelLiquidityFee(self, request, context):
        """Estimate the service fee for a channel liquidity request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestChannelRelease(self, request, context):
        """Ask the liquidity service to withdraw or cooperatively close channels on
        the client's behalf.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateRequestChannelReleaseFee(self, request, context):
        """Estimate the service fee for a channel release request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestChannelLeaseExtension(self, request, context):
        """Extend an existing asset lease on a channel.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateRequestChannelLeaseExtensionFee(self, request, context):
        """Estimate the service fee for a lease extension request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LiquidityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLiquidityServiceInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLiquidityServiceInfo,
                    request_deserializer=liquidity__pb2.GetLiquidityServiceInfoRequest.FromString,
                    response_serializer=liquidity__pb2.GetLiquidityServiceInfoResponse.SerializeToString,
            ),
            'GetLeaseableAssetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLeaseableAssetInfo,
                    request_deserializer=liquidity__pb2.GetLeaseableAssetInfoRequest.FromString,
                    response_serializer=liquidity__pb2.GetLeaseableAssetInfoResponse.SerializeToString,
            ),
            'GetLeases': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLeases,
                    request_deserializer=liquidity__pb2.GetLeasesRequest.FromString,
                    response_serializer=liquidity__pb2.GetLeasesResponse.SerializeToString,
            ),
            'GetLeaseExpiries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLeaseExpiries,
                    request_deserializer=liquidity__pb2.GetLeaseExpiriesRequest.FromString,
                    response_serializer=liquidity__pb2.GetLeaseExpiriesResponse.SerializeToString,
            ),
            'GetFeePayments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeePayments,
                    request_deserializer=liquidity__pb2.GetFeePaymentsRequest.FromString,
                    response_serializer=liquidity__pb2.GetFeePaymentsResponse.SerializeToString,
            ),
            'RequestChannelLiquidity': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestChannelLiquidity,
                    request_deserializer=liquidity__pb2.RequestChannelLiquidityRequest.FromString,
                    response_serializer=liquidity__pb2.RequestChannelLiquidityResponse.SerializeToString,
            ),
            'EstimateRequestChannelLiquidityFee': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateRequestChannelLiquidityFee,
                    request_deserializer=liquidity__pb2.RequestChannelLiquidityRequest.FromString,
                    response_serializer=liquidity__pb2.EstimateRequestFeeResponse.SerializeToString,
            ),
            'RequestChannelRelease': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestChannelRelease,
                    request_deserializer=liquidity__pb2.RequestChannelReleaseRequest.FromString,
                    response_serializer=liquidity__pb2.RequestChannelReleaseResponse.SerializeToString,
            ),
            'EstimateRequestChannelReleaseFee': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateRequestChannelReleaseFee,
                    request_deserializer=liquidity__pb2.RequestChannelReleaseRequest.FromString,
                    response_serializer=liquidity__pb2.EstimateRequestFeeResponse.SerializeToString,
            ),
            'RequestChannelLeaseExtension': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestChannelLeaseExtension,
                    request_deserializer=liquidity__pb2.RequestChannelLeaseExtensionRequest.FromString,
                    response_serializer=liquidity__pb2.RequestChannelLeaseExtensionResponse.SerializeToString,
            ),
            'EstimateRequestChannelLeaseExtensionFee': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateRequestChannelLeaseExtensionFee,
                    request_deserializer=liquidity__pb2.RequestChannelLeaseExtensionRequest.FromString,
                    response_serializer=liquidity__pb2.EstimateRequestFeeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hydra_app.LiquidityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hydra_app.LiquidityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LiquidityService(object):
    """Channel liquidity service.

    Exposes Hydra App's service-backed channel liquidity surface. Hydra App
    completes fee settlement and any required local confirmations internally
    before returning the final operation result.

    JSON-RPC namespace: `liquidity`
    """

    @staticmethod
    def GetLiquidityServiceInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.LiquidityService/GetLiquidityServiceInfo',
            liquidity__pb2.GetLiquidityServiceInfoRequest.SerializeToString,
            liquidity__pb2.GetLiquidityServiceInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLeaseableAssetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.LiquidityService/GetLeaseableAssetInfo',
            liquidity__pb2.GetLeaseableAssetInfoRequest.SerializeToString,
            liquidity__pb2.GetLeaseableAssetInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLeases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.LiquidityService/GetLeases',
            liquidity__pb2.GetLeasesRequest.SerializeToString,
            liquidity__pb2.GetLeasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLeaseExpiries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.LiquidityService/GetLeaseExpiries',
            liquidity__pb2.GetLeaseExpiriesRequest.SerializeToString,
            liquidity__pb2.GetLeaseExpiriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFeePayments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.LiquidityService/GetFeePayments',
            liquidity__pb2.GetFeePaymentsRequest.SerializeToString,
            liquidity__pb2.GetFeePaymentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestChannelLiquidity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.LiquidityService/RequestChannelLiquidity',
            liquidity__pb2.RequestChannelLiquidityRequest.SerializeToString,
            liquidity__pb2.RequestChannelLiquidityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateRequestChannelLiquidityFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.LiquidityService/EstimateRequestChannelLiquidityFee',
            liquidity__pb2.RequestChannelLiquidityRequest.SerializeToString,
            liquidity__pb2.EstimateRequestFeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestChannelRelease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.LiquidityService/RequestChannelRelease',
            liquidity__pb2.RequestChannelReleaseRequest.SerializeToString,
            liquidity__pb2.RequestChannelReleaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateRequestChannelReleaseFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.LiquidityService/EstimateRequestChannelReleaseFee',
            liquidity__pb2.RequestChannelReleaseRequest.SerializeToString,
            liquidity__pb2.EstimateRequestFeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestChannelLeaseExtension(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.LiquidityService/RequestChannelLeaseExtension',
            liquidity__pb2.RequestChannelLeaseExtensionRequest.SerializeToString,
            liquidity__pb2.RequestChannelLeaseExtensionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateRequestChannelLeaseExtensionFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.LiquidityService/EstimateRequestChannelLeaseExtensionFee',
            liquidity__pb2.RequestChannelLeaseExtensionRequest.SerializeToString,
            liquidity__pb2.EstimateRequestFeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
