# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lib.hydra_pb import node_pb2 as node__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in node_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeServiceStub(object):
    """Off-chain node management service.

    Provides full control over the off-chain node: peer connections, channel
    lifecycle (open, deposit, withdraw, close, force-close, redeem),
    payments (channel payments, routed payments, invoices, hashlocks),
    and dual-funding.

    JSON-RPC namespace: `node`
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConnectToPeer = channel.unary_unary(
                '/hydra_app.NodeService/ConnectToPeer',
                request_serializer=node__pb2.ConnectToPeerRequest.SerializeToString,
                response_deserializer=node__pb2.ConnectToPeerResponse.FromString,
                _registered_method=True)
        self.DisconnectFromPeer = channel.unary_unary(
                '/hydra_app.NodeService/DisconnectFromPeer',
                request_serializer=node__pb2.DisconnectFromPeerRequest.SerializeToString,
                response_deserializer=node__pb2.DisconnectFromPeerResponse.FromString,
                _registered_method=True)
        self.GetConnectedPeers = channel.unary_unary(
                '/hydra_app.NodeService/GetConnectedPeers',
                request_serializer=node__pb2.GetConnectedPeersRequest.SerializeToString,
                response_deserializer=node__pb2.GetConnectedPeersResponse.FromString,
                _registered_method=True)
        self.IsPeerConnected = channel.unary_unary(
                '/hydra_app.NodeService/IsPeerConnected',
                request_serializer=node__pb2.IsPeerConnectedRequest.SerializeToString,
                response_deserializer=node__pb2.IsPeerConnectedResponse.FromString,
                _registered_method=True)
        self.ConnectToWatchtower = channel.unary_unary(
                '/hydra_app.NodeService/ConnectToWatchtower',
                request_serializer=node__pb2.ConnectToWatchtowerRequest.SerializeToString,
                response_deserializer=node__pb2.ConnectToWatchtowerResponse.FromString,
                _registered_method=True)
        self.GetConnectedWatchtowers = channel.unary_unary(
                '/hydra_app.NodeService/GetConnectedWatchtowers',
                request_serializer=node__pb2.GetConnectedWatchtowersRequest.SerializeToString,
                response_deserializer=node__pb2.GetConnectedWatchtowersResponse.FromString,
                _registered_method=True)
        self.GetNodePolicy = channel.unary_unary(
                '/hydra_app.NodeService/GetNodePolicy',
                request_serializer=node__pb2.GetNodePolicyRequest.SerializeToString,
                response_deserializer=node__pb2.GetNodePolicyResponse.FromString,
                _registered_method=True)
        self.GetChannelTerms = channel.unary_unary(
                '/hydra_app.NodeService/GetChannelTerms',
                request_serializer=node__pb2.GetChannelTermsRequest.SerializeToString,
                response_deserializer=node__pb2.GetChannelTermsResponse.FromString,
                _registered_method=True)
        self.GetChannelPolicy = channel.unary_unary(
                '/hydra_app.NodeService/GetChannelPolicy',
                request_serializer=node__pb2.GetChannelPolicyRequest.SerializeToString,
                response_deserializer=node__pb2.GetChannelPolicyResponse.FromString,
                _registered_method=True)
        self.GetZeroConfWhitelist = channel.unary_unary(
                '/hydra_app.NodeService/GetZeroConfWhitelist',
                request_serializer=node__pb2.GetZeroConfWhitelistRequest.SerializeToString,
                response_deserializer=node__pb2.GetZeroConfWhitelistResponse.FromString,
                _registered_method=True)
        self.AddPeerToZeroConfWhitelist = channel.unary_unary(
                '/hydra_app.NodeService/AddPeerToZeroConfWhitelist',
                request_serializer=node__pb2.AddPeerToZeroConfWhitelistRequest.SerializeToString,
                response_deserializer=node__pb2.AddPeerToZeroConfWhitelistResponse.FromString,
                _registered_method=True)
        self.RemovePeerFromZeroConfWhitelist = channel.unary_unary(
                '/hydra_app.NodeService/RemovePeerFromZeroConfWhitelist',
                request_serializer=node__pb2.RemovePeerFromZeroConfWhitelistRequest.SerializeToString,
                response_deserializer=node__pb2.RemovePeerFromZeroConfWhitelistResponse.FromString,
                _registered_method=True)
        self.GetBlacklist = channel.unary_unary(
                '/hydra_app.NodeService/GetBlacklist',
                request_serializer=node__pb2.GetBlacklistRequest.SerializeToString,
                response_deserializer=node__pb2.GetBlacklistResponse.FromString,
                _registered_method=True)
        self.AddPeerToBlacklist = channel.unary_unary(
                '/hydra_app.NodeService/AddPeerToBlacklist',
                request_serializer=node__pb2.AddPeerToBlacklistRequest.SerializeToString,
                response_deserializer=node__pb2.AddPeerToBlacklistResponse.FromString,
                _registered_method=True)
        self.RemovePeerFromBlacklist = channel.unary_unary(
                '/hydra_app.NodeService/RemovePeerFromBlacklist',
                request_serializer=node__pb2.RemovePeerFromBlacklistRequest.SerializeToString,
                response_deserializer=node__pb2.RemovePeerFromBlacklistResponse.FromString,
                _registered_method=True)
        self.EstimateOpenChannelFee = channel.unary_unary(
                '/hydra_app.NodeService/EstimateOpenChannelFee',
                request_serializer=node__pb2.EstimateOpenChannelFeeRequest.SerializeToString,
                response_deserializer=node__pb2.EstimateOpenChannelFeeResponse.FromString,
                _registered_method=True)
        self.OpenChannel = channel.unary_unary(
                '/hydra_app.NodeService/OpenChannel',
                request_serializer=node__pb2.OpenChannelRequest.SerializeToString,
                response_deserializer=node__pb2.OpenChannelResponse.FromString,
                _registered_method=True)
        self.EstimateDepositChannelFee = channel.unary_unary(
                '/hydra_app.NodeService/EstimateDepositChannelFee',
                request_serializer=node__pb2.EstimateDepositChannelFeeRequest.SerializeToString,
                response_deserializer=node__pb2.EstimateDepositChannelFeeResponse.FromString,
                _registered_method=True)
        self.DepositChannel = channel.unary_unary(
                '/hydra_app.NodeService/DepositChannel',
                request_serializer=node__pb2.DepositChannelRequest.SerializeToString,
                response_deserializer=node__pb2.DepositChannelResponse.FromString,
                _registered_method=True)
        self.EstimateWithdrawChannelFee = channel.unary_unary(
                '/hydra_app.NodeService/EstimateWithdrawChannelFee',
                request_serializer=node__pb2.EstimateWithdrawChannelFeeRequest.SerializeToString,
                response_deserializer=node__pb2.EstimateWithdrawChannelFeeResponse.FromString,
                _registered_method=True)
        self.WithdrawChannel = channel.unary_unary(
                '/hydra_app.NodeService/WithdrawChannel',
                request_serializer=node__pb2.WithdrawChannelRequest.SerializeToString,
                response_deserializer=node__pb2.WithdrawChannelResponse.FromString,
                _registered_method=True)
        self.EstimateUpdateChannelFee = channel.unary_unary(
                '/hydra_app.NodeService/EstimateUpdateChannelFee',
                request_serializer=node__pb2.EstimateUpdateChannelFeeRequest.SerializeToString,
                response_deserializer=node__pb2.EstimateUpdateChannelFeeResponse.FromString,
                _registered_method=True)
        self.UpdateChannel = channel.unary_unary(
                '/hydra_app.NodeService/UpdateChannel',
                request_serializer=node__pb2.UpdateChannelRequest.SerializeToString,
                response_deserializer=node__pb2.UpdateChannelResponse.FromString,
                _registered_method=True)
        self.EstimateCloseChannelFee = channel.unary_unary(
                '/hydra_app.NodeService/EstimateCloseChannelFee',
                request_serializer=node__pb2.EstimateCloseChannelFeeRequest.SerializeToString,
                response_deserializer=node__pb2.EstimateCloseChannelFeeResponse.FromString,
                _registered_method=True)
        self.CloseChannel = channel.unary_unary(
                '/hydra_app.NodeService/CloseChannel',
                request_serializer=node__pb2.CloseChannelRequest.SerializeToString,
                response_deserializer=node__pb2.CloseChannelResponse.FromString,
                _registered_method=True)
        self.EstimateForceCloseChannelFee = channel.unary_unary(
                '/hydra_app.NodeService/EstimateForceCloseChannelFee',
                request_serializer=node__pb2.EstimateForceCloseChannelFeeRequest.SerializeToString,
                response_deserializer=node__pb2.EstimateForceCloseChannelFeeResponse.FromString,
                _registered_method=True)
        self.ForceCloseChannel = channel.unary_unary(
                '/hydra_app.NodeService/ForceCloseChannel',
                request_serializer=node__pb2.ForceCloseChannelRequest.SerializeToString,
                response_deserializer=node__pb2.ForceCloseChannelResponse.FromString,
                _registered_method=True)
        self.EstimateRedeemClosedChannelFee = channel.unary_unary(
                '/hydra_app.NodeService/EstimateRedeemClosedChannelFee',
                request_serializer=node__pb2.EstimateRedeemClosedChannelFeeRequest.SerializeToString,
                response_deserializer=node__pb2.EstimateRedeemClosedChannelFeeResponse.FromString,
                _registered_method=True)
        self.RedeemClosedChannel = channel.unary_unary(
                '/hydra_app.NodeService/RedeemClosedChannel',
                request_serializer=node__pb2.RedeemClosedChannelRequest.SerializeToString,
                response_deserializer=node__pb2.RedeemClosedChannelResponse.FromString,
                _registered_method=True)
        self.SendChannelPayment = channel.unary_unary(
                '/hydra_app.NodeService/SendChannelPayment',
                request_serializer=node__pb2.SendChannelPaymentRequest.SerializeToString,
                response_deserializer=node__pb2.SendChannelPaymentResponse.FromString,
                _registered_method=True)
        self.EstimateSendPaymentFee = channel.unary_unary(
                '/hydra_app.NodeService/EstimateSendPaymentFee',
                request_serializer=node__pb2.EstimateSendPaymentFeeRequest.SerializeToString,
                response_deserializer=node__pb2.EstimateSendPaymentFeeResponse.FromString,
                _registered_method=True)
        self.SendPayment = channel.unary_unary(
                '/hydra_app.NodeService/SendPayment',
                request_serializer=node__pb2.SendPaymentRequest.SerializeToString,
                response_deserializer=node__pb2.SendPaymentResponse.FromString,
                _registered_method=True)
        self.CreateInvoice = channel.unary_unary(
                '/hydra_app.NodeService/CreateInvoice',
                request_serializer=node__pb2.CreateInvoiceRequest.SerializeToString,
                response_deserializer=node__pb2.CreateInvoiceResponse.FromString,
                _registered_method=True)
        self.DecodeInvoice = channel.unary_unary(
                '/hydra_app.NodeService/DecodeInvoice',
                request_serializer=node__pb2.DecodeInvoiceRequest.SerializeToString,
                response_deserializer=node__pb2.DecodeInvoiceResponse.FromString,
                _registered_method=True)
        self.EstimatePayInvoiceFee = channel.unary_unary(
                '/hydra_app.NodeService/EstimatePayInvoiceFee',
                request_serializer=node__pb2.EstimatePayInvoiceFeeRequest.SerializeToString,
                response_deserializer=node__pb2.EstimatePayInvoiceFeeResponse.FromString,
                _registered_method=True)
        self.PayInvoice = channel.unary_unary(
                '/hydra_app.NodeService/PayInvoice',
                request_serializer=node__pb2.PayInvoiceRequest.SerializeToString,
                response_deserializer=node__pb2.PayInvoiceResponse.FromString,
                _registered_method=True)
        self.EstimatePayEmptyInvoiceFee = channel.unary_unary(
                '/hydra_app.NodeService/EstimatePayEmptyInvoiceFee',
                request_serializer=node__pb2.EstimatePayEmptyInvoiceFeeRequest.SerializeToString,
                response_deserializer=node__pb2.EstimatePayEmptyInvoiceFeeResponse.FromString,
                _registered_method=True)
        self.PayEmptyInvoice = channel.unary_unary(
                '/hydra_app.NodeService/PayEmptyInvoice',
                request_serializer=node__pb2.PayEmptyInvoiceRequest.SerializeToString,
                response_deserializer=node__pb2.PayEmptyInvoiceResponse.FromString,
                _registered_method=True)
        self.ResolveHashlockPayment = channel.unary_unary(
                '/hydra_app.NodeService/ResolveHashlockPayment',
                request_serializer=node__pb2.ResolveHashlockPaymentRequest.SerializeToString,
                response_deserializer=node__pb2.ResolveHashlockPaymentResponse.FromString,
                _registered_method=True)
        self.RejectPayment = channel.unary_unary(
                '/hydra_app.NodeService/RejectPayment',
                request_serializer=node__pb2.RejectPaymentRequest.SerializeToString,
                response_deserializer=node__pb2.RejectPaymentResponse.FromString,
                _registered_method=True)
        self.SetFundingAllowance = channel.unary_unary(
                '/hydra_app.NodeService/SetFundingAllowance',
                request_serializer=node__pb2.SetFundingAllowanceRequest.SerializeToString,
                response_deserializer=node__pb2.SetFundingAllowanceResponse.FromString,
                _registered_method=True)
        self.GetFundingAllowance = channel.unary_unary(
                '/hydra_app.NodeService/GetFundingAllowance',
                request_serializer=node__pb2.GetFundingAllowanceRequest.SerializeToString,
                response_deserializer=node__pb2.GetFundingAllowanceResponse.FromString,
                _registered_method=True)
        self.IncreaseFundingAllowance = channel.unary_unary(
                '/hydra_app.NodeService/IncreaseFundingAllowance',
                request_serializer=node__pb2.IncreaseFundingAllowanceRequest.SerializeToString,
                response_deserializer=node__pb2.IncreaseFundingAllowanceResponse.FromString,
                _registered_method=True)
        self.DecreaseFundingAllowance = channel.unary_unary(
                '/hydra_app.NodeService/DecreaseFundingAllowance',
                request_serializer=node__pb2.DecreaseFundingAllowanceRequest.SerializeToString,
                response_deserializer=node__pb2.DecreaseFundingAllowanceResponse.FromString,
                _registered_method=True)
        self.RevokeFundingAllowance = channel.unary_unary(
                '/hydra_app.NodeService/RevokeFundingAllowance',
                request_serializer=node__pb2.RevokeFundingAllowanceRequest.SerializeToString,
                response_deserializer=node__pb2.RevokeFundingAllowanceResponse.FromString,
                _registered_method=True)
        self.BatchChannelOperations = channel.unary_unary(
                '/hydra_app.NodeService/BatchChannelOperations',
                request_serializer=node__pb2.BatchChannelOperationsRequest.SerializeToString,
                response_deserializer=node__pb2.BatchChannelOperationsResponse.FromString,
                _registered_method=True)
        self.EstimateBatchChannelOperationsFee = channel.unary_unary(
                '/hydra_app.NodeService/EstimateBatchChannelOperationsFee',
                request_serializer=node__pb2.EstimateBatchChannelOperationsFeeRequest.SerializeToString,
                response_deserializer=node__pb2.EstimateBatchChannelOperationsFeeResponse.FromString,
                _registered_method=True)
        self.EstimateSimulatedChannelOperationFee = channel.unary_unary(
                '/hydra_app.NodeService/EstimateSimulatedChannelOperationFee',
                request_serializer=node__pb2.EstimateSimulatedChannelOperationFeeRequest.SerializeToString,
                response_deserializer=node__pb2.EstimateSimulatedChannelOperationFeeResponse.FromString,
                _registered_method=True)
        self.EstimateSimulatedChannelOperationsFee = channel.unary_unary(
                '/hydra_app.NodeService/EstimateSimulatedChannelOperationsFee',
                request_serializer=node__pb2.EstimateSimulatedChannelOperationsFeeRequest.SerializeToString,
                response_deserializer=node__pb2.EstimateSimulatedChannelOperationsFeeResponse.FromString,
                _registered_method=True)


class NodeServiceServicer(object):
    """Off-chain node management service.

    Provides full control over the off-chain node: peer connections, channel
    lifecycle (open, deposit, withdraw, close, force-close, redeem),
    payments (channel payments, routed payments, invoices, hashlocks),
    and dual-funding.

    JSON-RPC namespace: `node`
    """

    def ConnectToPeer(self, request, context):
        """Connect to a peer on a specific network.
        This allows the node to establish a connection with another node
        for communication and channel management.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectFromPeer(self, request, context):
        """Disconnect from a peer on a specific network.
        This allows the node to terminate the connection with another node.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConnectedPeers(self, request, context):
        """Get the list of connected peers on a specific network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsPeerConnected(self, request, context):
        """Check if a peer is connected on a specific network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectToWatchtower(self, request, context):
        """Attach this node to a watchtower on a specific network.

        A watchtower holds the states and revocations this node signs, so
        that a node which loses its local history can be handed back the
        coverage it gave away, and so that a channel stays defended while
        this node is offline. The session is separate from the ordinary
        peer session: the same remote node may be both a channel peer and
        a watchtower, and the two connections are independent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConnectedWatchtowers(self, request, context):
        """List the watchtowers this node currently has a session with.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodePolicy(self, request, context):
        """Read this node's policy configuration for the given asset.

        A "node policy" aggregates every parameter another party needs to
        know before negotiating a channel with this node: reserve rules,
        routing rules, channel timing rules, etc. Sub-messages are added
        in a backwards-compatible way as new policy categories are
        exposed by `NodeConfig` / per-protocol config traits.

        Used by liquidity providers (and any third party that wants to
        size on-chain deposits accurately) to predict the exact runtime
        reserve, routing fees, and payment ceilings the channel will be
        subject to.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChannelTerms(self, request, context):
        """Read the terms one of this node's channels actually carries.

        Sibling to GetNodePolicy, which answers what this node WILL negotiate
        before a channel exists. This answers what a channel DID: the terms it
        is held to as a whole, and each of its asset channels' own — each
        side's announcement, already combined by whatever rule the protocol
        applies, oriented from this node's point of view.

        Changes by announcement — an auth handshake, a gossip policy update, a
        config reconciliation at boot — and not by payment, so it is cacheable
        with a TTL. Balances change every payment and are on the channel
        listing, which this deliberately does not repeat.

        Used by anyone that has to price or size against terms the node
        enforces: a liquidity provider valuing the fees a channel earns, a
        client sizing a payment against the ceiling the peer will admit or the
        deadline the channel can hold.

        Answers for every channel the node knows, closed ones included — a
        closed channel's terms are what it was held to, not an offer to route
        over it. NOT_FOUND for a channel this node does not know.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChannelPolicy(self, request, context):
        """Deprecated: superseded by GetChannelTerms, which reports the same asset
        terms under the channel they belong to, together with the channel's
        own. Served unchanged until it is removed: the terms of every asset
        channel the filters select, one entry each, over the same channels the
        channel listing returns.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetZeroConfWhitelist(self, request, context):
        """Returns the zero-confirmation whitelist for the selected network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPeerToZeroConfWhitelist(self, request, context):
        """Adds a peer to the zero-confirmation whitelist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemovePeerFromZeroConfWhitelist(self, request, context):
        """Removes a peer from the zero-confirmation whitelist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlacklist(self, request, context):
        """Returns the peer connection blacklist for the selected network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPeerToBlacklist(self, request, context):
        """Adds a peer to the connection blacklist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemovePeerFromBlacklist(self, request, context):
        """Removes a peer from the connection blacklist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateOpenChannelFee(self, request, context):
        """Estimate the onchain fee for opening a channel with a specific peer.

        Fails when the amount plus its on-chain fee exceeds the spendable
        balance, rather than quoting a fee for a transaction that cannot be
        built. An `Exact` amount within a fee of the whole balance is therefore
        a refusal, not a quote: to fund everything, send `DepositAmount.All`,
        which takes the fee out of the amount instead of adding it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenChannel(self, request, context):
        """Open a channel with a specific peer on a specific network.
        This operation will create a channel and allocate assets to it.
        The channel will be funded with the specified asset amounts.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateDepositChannelFee(self, request, context):
        """Estimate the onchain fee for depositing assets into an existing channel.

        Fails when the amount plus its on-chain fee exceeds the spendable
        balance, rather than quoting a fee for a transaction that cannot be
        built. An `Exact` amount within a fee of the whole balance is therefore
        a refusal, not a quote: to fund everything, send `DepositAmount.All`,
        which takes the fee out of the amount instead of adding it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DepositChannel(self, request, context):
        """Deposit assets into an existing channel on a specific network.
        This operation will add more assets to the channel, increasing its
        capacity for future transactions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateWithdrawChannelFee(self, request, context):
        """Estimate the onchain fee for withdrawing assets from an existing channel.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WithdrawChannel(self, request, context):
        """Withdraw assets from an existing channel on a specific network.
        This operation will remove assets from the channel, reducing its
        capacity for future transactions.
        The assets will be sent back to the respective parties.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateUpdateChannelFee(self, request, context):
        """Estimate the onchain fee for a generic update of an existing channel.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateChannel(self, request, context):
        """Update an existing channel on a specific network.
        Each side's wallet may deposit or withdraw independently, and part of
        the resulting balance may be credited across in the state co-signed
        alongside the update. A deposit and a withdrawal are the two shapes of
        this that have their own calls; every other combination needs this one.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateCloseChannelFee(self, request, context):
        """Estimate the onchain fee for closing a channel.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseChannel(self, request, context):
        """Close a channel on a specific network.
        This operation will settle the channel and return the assets to
        the respective parties.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateForceCloseChannelFee(self, request, context):
        """Estimate the onchain fee for force-closing a channel.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForceCloseChannel(self, request, context):
        """Force-close a channel on a specific network.
        This operation will close the channel without waiting for the
        normal settlement process. It is typically used in cases where
        the channel is stuck or one party is unresponsive.
        The assets will be spendable only after a dispute period.
        Depending on the protocol, this may require an additional
        transaction to redeem the assets after the dispute period expires.
        This operation may incur higher fees than a normal close.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateRedeemClosedChannelFee(self, request, context):
        """Estimate the onchain fee for redeeming a closed channel.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RedeemClosedChannel(self, request, context):
        """Redeem a closed channel on a specific network.
        This operation will settle the channel and return the assets to
        the respective parties. It is used after a force-close
        operation to finalize the settlement process and withdraw the
        assets from the channel.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendChannelPayment(self, request, context):
        """Send a payment through a specific channel on a specific network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateSendPaymentFee(self, request, context):
        """Estimate the offchain fee for sending a payment on a
        network. This operation will find the best route for the payment
        and calculate the fee for sending the payment through the
        network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPayment(self, request, context):
        """Send a payment on a specific network. This operation will find the
        best route for the payment and send the payment through the
        network. The payment will be routed through the channels and
        nodes in the network to reach the recipient.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateInvoice(self, request, context):
        """Create an invoice for a specific asset on a network.
        This operation will generate a payment request that can be
        shared with the payer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecodeInvoice(self, request, context):
        """Decode an invoice to retrieve its details.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimatePayInvoiceFee(self, request, context):
        """Estimate the offchain fee for paying an invoice.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PayInvoice(self, request, context):
        """Pay an invoice on a specific network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimatePayEmptyInvoiceFee(self, request, context):
        """Estimate the offchain fee for paying an empty invoice by providing the
        amount to pay.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PayEmptyInvoice(self, request, context):
        """Pay an empty invoice on a specific network by providing the
        amount to pay.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveHashlockPayment(self, request, context):
        """Resolve a hashlock payment by providing the payment preimage.
        This operation will finalize the offchain payment and allow the recipient
        to claim the funds.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectPayment(self, request, context):
        """Reject a hashlock payment on a specific network.
        This operation will cancel the payment and unlock the funds for
        the sender.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFundingAllowance(self, request, context):
        """Set the funding allowance for a specific peer on a network.
        This replaces any existing allowance. The allowance controls the maximum
        deposit and payment amounts that the counterparty is permitted to initiate
        on our behalf.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFundingAllowance(self, request, context):
        """Get the current funding allowance for a specific peer on a network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncreaseFundingAllowance(self, request, context):
        """Increase the funding allowance for a specific peer on a network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecreaseFundingAllowance(self, request, context):
        """Decrease the funding allowance for a specific peer on a network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeFundingAllowance(self, request, context):
        """Revoke all funding allowances for a specific peer on a network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchChannelOperations(self, request, context):
        """Atomically execute a batch of on-chain channel operations in a single
        transaction. Supported operations: open, deposit, withdraw, close,
        force-close and redeem.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateBatchChannelOperationsFee(self, request, context):
        """Estimate the total on-chain fee for a batch of channel operations.

        Fails when the amount plus its on-chain fee exceeds the spendable
        balance, rather than quoting a fee for a transaction that cannot be
        built. An `Exact` amount within a fee of the whole balance is therefore
        a refusal, not a quote: to fund everything, send `DepositAmount.All`,
        which takes the fee out of the amount instead of adding it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateSimulatedChannelOperationFee(self, request, context):
        """Estimate the on-chain fee of a single operation over a simulated channel
        snapshot.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateSimulatedChannelOperationsFee(self, request, context):
        """Estimate the total fee of multiple simulated channel-operation requests.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConnectToPeer': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectToPeer,
                    request_deserializer=node__pb2.ConnectToPeerRequest.FromString,
                    response_serializer=node__pb2.ConnectToPeerResponse.SerializeToString,
            ),
            'DisconnectFromPeer': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectFromPeer,
                    request_deserializer=node__pb2.DisconnectFromPeerRequest.FromString,
                    response_serializer=node__pb2.DisconnectFromPeerResponse.SerializeToString,
            ),
            'GetConnectedPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnectedPeers,
                    request_deserializer=node__pb2.GetConnectedPeersRequest.FromString,
                    response_serializer=node__pb2.GetConnectedPeersResponse.SerializeToString,
            ),
            'IsPeerConnected': grpc.unary_unary_rpc_method_handler(
                    servicer.IsPeerConnected,
                    request_deserializer=node__pb2.IsPeerConnectedRequest.FromString,
                    response_serializer=node__pb2.IsPeerConnectedResponse.SerializeToString,
            ),
            'ConnectToWatchtower': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectToWatchtower,
                    request_deserializer=node__pb2.ConnectToWatchtowerRequest.FromString,
                    response_serializer=node__pb2.ConnectToWatchtowerResponse.SerializeToString,
            ),
            'GetConnectedWatchtowers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnectedWatchtowers,
                    request_deserializer=node__pb2.GetConnectedWatchtowersRequest.FromString,
                    response_serializer=node__pb2.GetConnectedWatchtowersResponse.SerializeToString,
            ),
            'GetNodePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodePolicy,
                    request_deserializer=node__pb2.GetNodePolicyRequest.FromString,
                    response_serializer=node__pb2.GetNodePolicyResponse.SerializeToString,
            ),
            'GetChannelTerms': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChannelTerms,
                    request_deserializer=node__pb2.GetChannelTermsRequest.FromString,
                    response_serializer=node__pb2.GetChannelTermsResponse.SerializeToString,
            ),
            'GetChannelPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChannelPolicy,
                    request_deserializer=node__pb2.GetChannelPolicyRequest.FromString,
                    response_serializer=node__pb2.GetChannelPolicyResponse.SerializeToString,
            ),
            'GetZeroConfWhitelist': grpc.unary_unary_rpc_method_handler(
                    servicer.GetZeroConfWhitelist,
                    request_deserializer=node__pb2.GetZeroConfWhitelistRequest.FromString,
                    response_serializer=node__pb2.GetZeroConfWhitelistResponse.SerializeToString,
            ),
            'AddPeerToZeroConfWhitelist': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPeerToZeroConfWhitelist,
                    request_deserializer=node__pb2.AddPeerToZeroConfWhitelistRequest.FromString,
                    response_serializer=node__pb2.AddPeerToZeroConfWhitelistResponse.SerializeToString,
            ),
            'RemovePeerFromZeroConfWhitelist': grpc.unary_unary_rpc_method_handler(
                    servicer.RemovePeerFromZeroConfWhitelist,
                    request_deserializer=node__pb2.RemovePeerFromZeroConfWhitelistRequest.FromString,
                    response_serializer=node__pb2.RemovePeerFromZeroConfWhitelistResponse.SerializeToString,
            ),
            'GetBlacklist': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlacklist,
                    request_deserializer=node__pb2.GetBlacklistRequest.FromString,
                    response_serializer=node__pb2.GetBlacklistResponse.SerializeToString,
            ),
            'AddPeerToBlacklist': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPeerToBlacklist,
                    request_deserializer=node__pb2.AddPeerToBlacklistRequest.FromString,
                    response_serializer=node__pb2.AddPeerToBlacklistResponse.SerializeToString,
            ),
            'RemovePeerFromBlacklist': grpc.unary_unary_rpc_method_handler(
                    servicer.RemovePeerFromBlacklist,
                    request_deserializer=node__pb2.RemovePeerFromBlacklistRequest.FromString,
                    response_serializer=node__pb2.RemovePeerFromBlacklistResponse.SerializeToString,
            ),
            'EstimateOpenChannelFee': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateOpenChannelFee,
                    request_deserializer=node__pb2.EstimateOpenChannelFeeRequest.FromString,
                    response_serializer=node__pb2.EstimateOpenChannelFeeResponse.SerializeToString,
            ),
            'OpenChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenChannel,
                    request_deserializer=node__pb2.OpenChannelRequest.FromString,
                    response_serializer=node__pb2.OpenChannelResponse.SerializeToString,
            ),
            'EstimateDepositChannelFee': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateDepositChannelFee,
                    request_deserializer=node__pb2.EstimateDepositChannelFeeRequest.FromString,
                    response_serializer=node__pb2.EstimateDepositChannelFeeResponse.SerializeToString,
            ),
            'DepositChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.DepositChannel,
                    request_deserializer=node__pb2.DepositChannelRequest.FromString,
                    response_serializer=node__pb2.DepositChannelResponse.SerializeToString,
            ),
            'EstimateWithdrawChannelFee': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateWithdrawChannelFee,
                    request_deserializer=node__pb2.EstimateWithdrawChannelFeeRequest.FromString,
                    response_serializer=node__pb2.EstimateWithdrawChannelFeeResponse.SerializeToString,
            ),
            'WithdrawChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.WithdrawChannel,
                    request_deserializer=node__pb2.WithdrawChannelRequest.FromString,
                    response_serializer=node__pb2.WithdrawChannelResponse.SerializeToString,
            ),
            'EstimateUpdateChannelFee': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateUpdateChannelFee,
                    request_deserializer=node__pb2.EstimateUpdateChannelFeeRequest.FromString,
                    response_serializer=node__pb2.EstimateUpdateChannelFeeResponse.SerializeToString,
            ),
            'UpdateChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateChannel,
                    request_deserializer=node__pb2.UpdateChannelRequest.FromString,
                    response_serializer=node__pb2.UpdateChannelResponse.SerializeToString,
            ),
            'EstimateCloseChannelFee': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateCloseChannelFee,
                    request_deserializer=node__pb2.EstimateCloseChannelFeeRequest.FromString,
                    response_serializer=node__pb2.EstimateCloseChannelFeeResponse.SerializeToString,
            ),
            'CloseChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseChannel,
                    request_deserializer=node__pb2.CloseChannelRequest.FromString,
                    response_serializer=node__pb2.CloseChannelResponse.SerializeToString,
            ),
            'EstimateForceCloseChannelFee': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateForceCloseChannelFee,
                    request_deserializer=node__pb2.EstimateForceCloseChannelFeeRequest.FromString,
                    response_serializer=node__pb2.EstimateForceCloseChannelFeeResponse.SerializeToString,
            ),
            'ForceCloseChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.ForceCloseChannel,
                    request_deserializer=node__pb2.ForceCloseChannelRequest.FromString,
                    response_serializer=node__pb2.ForceCloseChannelResponse.SerializeToString,
            ),
            'EstimateRedeemClosedChannelFee': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateRedeemClosedChannelFee,
                    request_deserializer=node__pb2.EstimateRedeemClosedChannelFeeRequest.FromString,
                    response_serializer=node__pb2.EstimateRedeemClosedChannelFeeResponse.SerializeToString,
            ),
            'RedeemClosedChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.RedeemClosedChannel,
                    request_deserializer=node__pb2.RedeemClosedChannelRequest.FromString,
                    response_serializer=node__pb2.RedeemClosedChannelResponse.SerializeToString,
            ),
            'SendChannelPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.SendChannelPayment,
                    request_deserializer=node__pb2.SendChannelPaymentRequest.FromString,
                    response_serializer=node__pb2.SendChannelPaymentResponse.SerializeToString,
            ),
            'EstimateSendPaymentFee': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateSendPaymentFee,
                    request_deserializer=node__pb2.EstimateSendPaymentFeeRequest.FromString,
                    response_serializer=node__pb2.EstimateSendPaymentFeeResponse.SerializeToString,
            ),
            'SendPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPayment,
                    request_deserializer=node__pb2.SendPaymentRequest.FromString,
                    response_serializer=node__pb2.SendPaymentResponse.SerializeToString,
            ),
            'CreateInvoice': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInvoice,
                    request_deserializer=node__pb2.CreateInvoiceRequest.FromString,
                    response_serializer=node__pb2.CreateInvoiceResponse.SerializeToString,
            ),
            'DecodeInvoice': grpc.unary_unary_rpc_method_handler(
                    servicer.DecodeInvoice,
                    request_deserializer=node__pb2.DecodeInvoiceRequest.FromString,
                    response_serializer=node__pb2.DecodeInvoiceResponse.SerializeToString,
            ),
            'EstimatePayInvoiceFee': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimatePayInvoiceFee,
                    request_deserializer=node__pb2.EstimatePayInvoiceFeeRequest.FromString,
                    response_serializer=node__pb2.EstimatePayInvoiceFeeResponse.SerializeToString,
            ),
            'PayInvoice': grpc.unary_unary_rpc_method_handler(
                    servicer.PayInvoice,
                    request_deserializer=node__pb2.PayInvoiceRequest.FromString,
                    response_serializer=node__pb2.PayInvoiceResponse.SerializeToString,
            ),
            'EstimatePayEmptyInvoiceFee': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimatePayEmptyInvoiceFee,
                    request_deserializer=node__pb2.EstimatePayEmptyInvoiceFeeRequest.FromString,
                    response_serializer=node__pb2.EstimatePayEmptyInvoiceFeeResponse.SerializeToString,
            ),
            'PayEmptyInvoice': grpc.unary_unary_rpc_method_handler(
                    servicer.PayEmptyInvoice,
                    request_deserializer=node__pb2.PayEmptyInvoiceRequest.FromString,
                    response_serializer=node__pb2.PayEmptyInvoiceResponse.SerializeToString,
            ),
            'ResolveHashlockPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveHashlockPayment,
                    request_deserializer=node__pb2.ResolveHashlockPaymentRequest.FromString,
                    response_serializer=node__pb2.ResolveHashlockPaymentResponse.SerializeToString,
            ),
            'RejectPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectPayment,
                    request_deserializer=node__pb2.RejectPaymentRequest.FromString,
                    response_serializer=node__pb2.RejectPaymentResponse.SerializeToString,
            ),
            'SetFundingAllowance': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFundingAllowance,
                    request_deserializer=node__pb2.SetFundingAllowanceRequest.FromString,
                    response_serializer=node__pb2.SetFundingAllowanceResponse.SerializeToString,
            ),
            'GetFundingAllowance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFundingAllowance,
                    request_deserializer=node__pb2.GetFundingAllowanceRequest.FromString,
                    response_serializer=node__pb2.GetFundingAllowanceResponse.SerializeToString,
            ),
            'IncreaseFundingAllowance': grpc.unary_unary_rpc_method_handler(
                    servicer.IncreaseFundingAllowance,
                    request_deserializer=node__pb2.IncreaseFundingAllowanceRequest.FromString,
                    response_serializer=node__pb2.IncreaseFundingAllowanceResponse.SerializeToString,
            ),
            'DecreaseFundingAllowance': grpc.unary_unary_rpc_method_handler(
                    servicer.DecreaseFundingAllowance,
                    request_deserializer=node__pb2.DecreaseFundingAllowanceRequest.FromString,
                    response_serializer=node__pb2.DecreaseFundingAllowanceResponse.SerializeToString,
            ),
            'RevokeFundingAllowance': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeFundingAllowance,
                    request_deserializer=node__pb2.RevokeFundingAllowanceRequest.FromString,
                    response_serializer=node__pb2.RevokeFundingAllowanceResponse.SerializeToString,
            ),
            'BatchChannelOperations': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchChannelOperations,
                    request_deserializer=node__pb2.BatchChannelOperationsRequest.FromString,
                    response_serializer=node__pb2.BatchChannelOperationsResponse.SerializeToString,
            ),
            'EstimateBatchChannelOperationsFee': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateBatchChannelOperationsFee,
                    request_deserializer=node__pb2.EstimateBatchChannelOperationsFeeRequest.FromString,
                    response_serializer=node__pb2.EstimateBatchChannelOperationsFeeResponse.SerializeToString,
            ),
            'EstimateSimulatedChannelOperationFee': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateSimulatedChannelOperationFee,
                    request_deserializer=node__pb2.EstimateSimulatedChannelOperationFeeRequest.FromString,
                    response_serializer=node__pb2.EstimateSimulatedChannelOperationFeeResponse.SerializeToString,
            ),
            'EstimateSimulatedChannelOperationsFee': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateSimulatedChannelOperationsFee,
                    request_deserializer=node__pb2.EstimateSimulatedChannelOperationsFeeRequest.FromString,
                    response_serializer=node__pb2.EstimateSimulatedChannelOperationsFeeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hydra_app.NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hydra_app.NodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """Off-chain node management service.

    Provides full control over the off-chain node: peer connections, channel
    lifecycle (open, deposit, withdraw, close, force-close, redeem),
    payments (channel payments, routed payments, invoices, hashlocks),
    and dual-funding.

    JSON-RPC namespace: `node`
    """

    @staticmethod
    def ConnectToPeer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/ConnectToPeer',
            node__pb2.ConnectToPeerRequest.SerializeToString,
            node__pb2.ConnectToPeerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisconnectFromPeer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/DisconnectFromPeer',
            node__pb2.DisconnectFromPeerRequest.SerializeToString,
            node__pb2.DisconnectFromPeerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConnectedPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/GetConnectedPeers',
            node__pb2.GetConnectedPeersRequest.SerializeToString,
            node__pb2.GetConnectedPeersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsPeerConnected(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/IsPeerConnected',
            node__pb2.IsPeerConnectedRequest.SerializeToString,
            node__pb2.IsPeerConnectedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConnectToWatchtower(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/ConnectToWatchtower',
            node__pb2.ConnectToWatchtowerRequest.SerializeToString,
            node__pb2.ConnectToWatchtowerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConnectedWatchtowers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/GetConnectedWatchtowers',
            node__pb2.GetConnectedWatchtowersRequest.SerializeToString,
            node__pb2.GetConnectedWatchtowersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/GetNodePolicy',
            node__pb2.GetNodePolicyRequest.SerializeToString,
            node__pb2.GetNodePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChannelTerms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/GetChannelTerms',
            node__pb2.GetChannelTermsRequest.SerializeToString,
            node__pb2.GetChannelTermsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChannelPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/GetChannelPolicy',
            node__pb2.GetChannelPolicyRequest.SerializeToString,
            node__pb2.GetChannelPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetZeroConfWhitelist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/GetZeroConfWhitelist',
            node__pb2.GetZeroConfWhitelistRequest.SerializeToString,
            node__pb2.GetZeroConfWhitelistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPeerToZeroConfWhitelist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/AddPeerToZeroConfWhitelist',
            node__pb2.AddPeerToZeroConfWhitelistRequest.SerializeToString,
            node__pb2.AddPeerToZeroConfWhitelistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemovePeerFromZeroConfWhitelist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/RemovePeerFromZeroConfWhitelist',
            node__pb2.RemovePeerFromZeroConfWhitelistRequest.SerializeToString,
            node__pb2.RemovePeerFromZeroConfWhitelistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBlacklist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/GetBlacklist',
            node__pb2.GetBlacklistRequest.SerializeToString,
            node__pb2.GetBlacklistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPeerToBlacklist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/AddPeerToBlacklist',
            node__pb2.AddPeerToBlacklistRequest.SerializeToString,
            node__pb2.AddPeerToBlacklistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemovePeerFromBlacklist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/RemovePeerFromBlacklist',
            node__pb2.RemovePeerFromBlacklistRequest.SerializeToString,
            node__pb2.RemovePeerFromBlacklistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateOpenChannelFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/EstimateOpenChannelFee',
            node__pb2.EstimateOpenChannelFeeRequest.SerializeToString,
            node__pb2.EstimateOpenChannelFeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/OpenChannel',
            node__pb2.OpenChannelRequest.SerializeToString,
            node__pb2.OpenChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateDepositChannelFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/EstimateDepositChannelFee',
            node__pb2.EstimateDepositChannelFeeRequest.SerializeToString,
            node__pb2.EstimateDepositChannelFeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DepositChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/DepositChannel',
            node__pb2.DepositChannelRequest.SerializeToString,
            node__pb2.DepositChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateWithdrawChannelFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/EstimateWithdrawChannelFee',
            node__pb2.EstimateWithdrawChannelFeeRequest.SerializeToString,
            node__pb2.EstimateWithdrawChannelFeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WithdrawChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/WithdrawChannel',
            node__pb2.WithdrawChannelRequest.SerializeToString,
            node__pb2.WithdrawChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateUpdateChannelFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/EstimateUpdateChannelFee',
            node__pb2.EstimateUpdateChannelFeeRequest.SerializeToString,
            node__pb2.EstimateUpdateChannelFeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/UpdateChannel',
            node__pb2.UpdateChannelRequest.SerializeToString,
            node__pb2.UpdateChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateCloseChannelFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/EstimateCloseChannelFee',
            node__pb2.EstimateCloseChannelFeeRequest.SerializeToString,
            node__pb2.EstimateCloseChannelFeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/CloseChannel',
            node__pb2.CloseChannelRequest.SerializeToString,
            node__pb2.CloseChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateForceCloseChannelFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/EstimateForceCloseChannelFee',
            node__pb2.EstimateForceCloseChannelFeeRequest.SerializeToString,
            node__pb2.EstimateForceCloseChannelFeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForceCloseChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/ForceCloseChannel',
            node__pb2.ForceCloseChannelRequest.SerializeToString,
            node__pb2.ForceCloseChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateRedeemClosedChannelFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/EstimateRedeemClosedChannelFee',
            node__pb2.EstimateRedeemClosedChannelFeeRequest.SerializeToString,
            node__pb2.EstimateRedeemClosedChannelFeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RedeemClosedChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/RedeemClosedChannel',
            node__pb2.RedeemClosedChannelRequest.SerializeToString,
            node__pb2.RedeemClosedChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendChannelPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/SendChannelPayment',
            node__pb2.SendChannelPaymentRequest.SerializeToString,
            node__pb2.SendChannelPaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateSendPaymentFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/EstimateSendPaymentFee',
            node__pb2.EstimateSendPaymentFeeRequest.SerializeToString,
            node__pb2.EstimateSendPaymentFeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/SendPayment',
            node__pb2.SendPaymentRequest.SerializeToString,
            node__pb2.SendPaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateInvoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/CreateInvoice',
            node__pb2.CreateInvoiceRequest.SerializeToString,
            node__pb2.CreateInvoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecodeInvoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/DecodeInvoice',
            node__pb2.DecodeInvoiceRequest.SerializeToString,
            node__pb2.DecodeInvoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimatePayInvoiceFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/EstimatePayInvoiceFee',
            node__pb2.EstimatePayInvoiceFeeRequest.SerializeToString,
            node__pb2.EstimatePayInvoiceFeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PayInvoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/PayInvoice',
            node__pb2.PayInvoiceRequest.SerializeToString,
            node__pb2.PayInvoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimatePayEmptyInvoiceFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/EstimatePayEmptyInvoiceFee',
            node__pb2.EstimatePayEmptyInvoiceFeeRequest.SerializeToString,
            node__pb2.EstimatePayEmptyInvoiceFeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PayEmptyInvoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/PayEmptyInvoice',
            node__pb2.PayEmptyInvoiceRequest.SerializeToString,
            node__pb2.PayEmptyInvoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveHashlockPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/ResolveHashlockPayment',
            node__pb2.ResolveHashlockPaymentRequest.SerializeToString,
            node__pb2.ResolveHashlockPaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/RejectPayment',
            node__pb2.RejectPaymentRequest.SerializeToString,
            node__pb2.RejectPaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetFundingAllowance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/SetFundingAllowance',
            node__pb2.SetFundingAllowanceRequest.SerializeToString,
            node__pb2.SetFundingAllowanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFundingAllowance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/GetFundingAllowance',
            node__pb2.GetFundingAllowanceRequest.SerializeToString,
            node__pb2.GetFundingAllowanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IncreaseFundingAllowance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/IncreaseFundingAllowance',
            node__pb2.IncreaseFundingAllowanceRequest.SerializeToString,
            node__pb2.IncreaseFundingAllowanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecreaseFundingAllowance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/DecreaseFundingAllowance',
            node__pb2.DecreaseFundingAllowanceRequest.SerializeToString,
            node__pb2.DecreaseFundingAllowanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeFundingAllowance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/RevokeFundingAllowance',
            node__pb2.RevokeFundingAllowanceRequest.SerializeToString,
            node__pb2.RevokeFundingAllowanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchChannelOperations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/BatchChannelOperations',
            node__pb2.BatchChannelOperationsRequest.SerializeToString,
            node__pb2.BatchChannelOperationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateBatchChannelOperationsFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/EstimateBatchChannelOperationsFee',
            node__pb2.EstimateBatchChannelOperationsFeeRequest.SerializeToString,
            node__pb2.EstimateBatchChannelOperationsFeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateSimulatedChannelOperationFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/EstimateSimulatedChannelOperationFee',
            node__pb2.EstimateSimulatedChannelOperationFeeRequest.SerializeToString,
            node__pb2.EstimateSimulatedChannelOperationFeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateSimulatedChannelOperationsFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.NodeService/EstimateSimulatedChannelOperationsFee',
            node__pb2.EstimateSimulatedChannelOperationsFeeRequest.SerializeToString,
            node__pb2.EstimateSimulatedChannelOperationsFeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
