# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: preimage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'preimage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lib.hydra_pb import primitives_pb2 as primitives__pb2
from lib.hydra_pb import fee_pb2 as fee__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epreimage.proto\x12\thydra_app\x1a\x10primitives.proto\x1a\tfee.proto\"V\n\x15SettlePreimageRequest\x12#\n\x07network\x18\x01 \x01(\x0b\x32\x12.hydra_app.Network\x12\x18\n\x10payment_preimage\x18\x02 \x01(\t\"\x18\n\x16SettlePreimageResponse\"\x98\x01\n\x19SettleHtlcPreimageRequest\x12#\n\x07network\x18\x01 \x01(\x0b\x32\x12.hydra_app.Network\x12\x18\n\x10payment_preimage\x18\x02 \x01(\t\x12-\n\nfee_option\x18\x03 \x01(\x0b\x32\x14.hydra_app.FeeOptionH\x00\x88\x01\x01\x42\r\n\x0b_fee_option\"+\n\x1aSettleHtlcPreimageResponse\x12\r\n\x05txids\x18\x01 \x03(\t2\xcf\x01\n\x0fPreimageService\x12W\n\x0eSettlePreimage\x12 .hydra_app.SettlePreimageRequest\x1a!.hydra_app.SettlePreimageResponse\"\x00\x12\x63\n\x12SettleHtlcPreimage\x12$.hydra_app.SettleHtlcPreimageRequest\x1a%.hydra_app.SettleHtlcPreimageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'preimage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETTLEPREIMAGEREQUEST']._serialized_start=58
  _globals['_SETTLEPREIMAGEREQUEST']._serialized_end=144
  _globals['_SETTLEPREIMAGERESPONSE']._serialized_start=146
  _globals['_SETTLEPREIMAGERESPONSE']._serialized_end=170
  _globals['_SETTLEHTLCPREIMAGEREQUEST']._serialized_start=173
  _globals['_SETTLEHTLCPREIMAGEREQUEST']._serialized_end=325
  _globals['_SETTLEHTLCPREIMAGERESPONSE']._serialized_start=327
  _globals['_SETTLEHTLCPREIMAGERESPONSE']._serialized_end=370
  _globals['_PREIMAGESERVICE']._serialized_start=373
  _globals['_PREIMAGESERVICE']._serialized_end=580
# @@protoc_insertion_point(module_scope)
