# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pricing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pricing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lib.hydra_pb import primitives_pb2 as primitives__pb2
from lib.hydra_pb import currency_pb2 as currency__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpricing.proto\x12\thydra_app\x1a\x10primitives.proto\x1a\x0e\x63urrency.proto\"\x81\x01\n\x18GetAssetFiatPriceRequest\x12#\n\x07network\x18\x01 \x01(\x0b\x32\x12.hydra_app.Network\x12\x10\n\x08\x61sset_id\x18\x02 \x01(\t\x12.\n\rfiat_currency\x18\x03 \x01(\x0e\x32\x17.hydra_app.FiatCurrency\"S\n\x19GetAssetFiatPriceResponse\x12,\n\x05price\x18\x01 \x01(\x0b\x32\x18.hydra_app.DecimalStringH\x00\x88\x01\x01\x42\x08\n\x06_price\"h\n GetAssetFiatPriceBySymbolRequest\x12\x14\n\x0c\x61sset_symbol\x18\x01 \x01(\t\x12.\n\rfiat_currency\x18\x02 \x01(\x0e\x32\x17.hydra_app.FiatCurrency\"[\n!GetAssetFiatPriceBySymbolResponse\x12,\n\x05price\x18\x01 \x01(\x0b\x32\x18.hydra_app.DecimalStringH\x00\x88\x01\x01\x42\x08\n\x06_price2\xec\x01\n\x0ePricingService\x12`\n\x11GetAssetFiatPrice\x12#.hydra_app.GetAssetFiatPriceRequest\x1a$.hydra_app.GetAssetFiatPriceResponse\"\x00\x12x\n\x19GetAssetFiatPriceBySymbol\x12+.hydra_app.GetAssetFiatPriceBySymbolRequest\x1a,.hydra_app.GetAssetFiatPriceBySymbolResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pricing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETASSETFIATPRICEREQUEST']._serialized_start=63
  _globals['_GETASSETFIATPRICEREQUEST']._serialized_end=192
  _globals['_GETASSETFIATPRICERESPONSE']._serialized_start=194
  _globals['_GETASSETFIATPRICERESPONSE']._serialized_end=277
  _globals['_GETASSETFIATPRICEBYSYMBOLREQUEST']._serialized_start=279
  _globals['_GETASSETFIATPRICEBYSYMBOLREQUEST']._serialized_end=383
  _globals['_GETASSETFIATPRICEBYSYMBOLRESPONSE']._serialized_start=385
  _globals['_GETASSETFIATPRICEBYSYMBOLRESPONSE']._serialized_end=476
  _globals['_PRICINGSERVICE']._serialized_start=479
  _globals['_PRICINGSERVICE']._serialized_end=715
# @@protoc_insertion_point(module_scope)
