# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lib.hydra_pb import swap_pb2 as swap__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in swap_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SwapServiceStub(object):
    """Swap service for performing cross-currency swap operations.

    Provides both basic swaps (requiring pre-existing off-chain balances)
    and "simple swaps" that automatically set up the necessary channels
    via deposits and/or leases before executing the swap.

    JSON-RPC namespace: `swap`
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EstimateSwap = channel.unary_unary(
                '/hydra_app.SwapService/EstimateSwap',
                request_serializer=swap__pb2.EstimateSwapRequest.SerializeToString,
                response_deserializer=swap__pb2.EstimateSwapResponse.FromString,
                _registered_method=True)
        self.Swap = channel.unary_unary(
                '/hydra_app.SwapService/Swap',
                request_serializer=swap__pb2.SwapRequest.SerializeToString,
                response_deserializer=swap__pb2.SwapResponse.FromString,
                _registered_method=True)
        self.EstimateSimpleSwap = channel.unary_unary(
                '/hydra_app.SwapService/EstimateSimpleSwap',
                request_serializer=swap__pb2.EstimateSimpleSwapRequest.SerializeToString,
                response_deserializer=swap__pb2.EstimateSimpleSwapResponse.FromString,
                _registered_method=True)
        self.SimpleSwap = channel.unary_unary(
                '/hydra_app.SwapService/SimpleSwap',
                request_serializer=swap__pb2.SimpleSwapRequest.SerializeToString,
                response_deserializer=swap__pb2.SimpleSwapResponse.FromString,
                _registered_method=True)
        self.CancelSimpleSwap = channel.unary_unary(
                '/hydra_app.SwapService/CancelSimpleSwap',
                request_serializer=swap__pb2.CancelSimpleSwapRequest.SerializeToString,
                response_deserializer=swap__pb2.CancelSimpleSwapResponse.FromString,
                _registered_method=True)
        self.SubscribeSimpleSwaps = channel.unary_stream(
                '/hydra_app.SwapService/SubscribeSimpleSwaps',
                request_serializer=swap__pb2.SubscribeSimpleSwapsRequest.SerializeToString,
                response_deserializer=swap__pb2.SimpleSwapUpdate.FromString,
                _registered_method=True)
        self.EstimateSimpleSwappableAmounts = channel.unary_unary(
                '/hydra_app.SwapService/EstimateSimpleSwappableAmounts',
                request_serializer=swap__pb2.EstimateSimpleSwappableAmountsRequest.SerializeToString,
                response_deserializer=swap__pb2.EstimateSimpleSwappableAmountsResponse.FromString,
                _registered_method=True)


class SwapServiceServicer(object):
    """Swap service for performing cross-currency swap operations.

    Provides both basic swaps (requiring pre-existing off-chain balances)
    and "simple swaps" that automatically set up the necessary channels
    via deposits and/or leases before executing the swap.

    JSON-RPC namespace: `swap`
    """

    def EstimateSwap(self, request, context):
        """Estimate the order matching for a swap operation between two currencies for
        a certain amount. For a market swap to be performed, the user must have
        enough offchain balance for both the sending and receiving currencies.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Swap(self, request, context):
        """Perform a swap operation between two currencies for a certain amount. The
        user must have enough offchain balance for both the sending and receiving
        currencies.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateSimpleSwap(self, request, context):
        """Estimate the fees for setting up channels (via openings, deposits and/or
        leases) to then be able to perform a swap operation between two currencies
        for a certain amount. This also returns the estimate of the order matching
        in the current orderbook state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimpleSwap(self, request, context):
        """This method is used to automatically set up channels (via openings,
        deposits and/or leases) to then be able to perform a swap operation
        between two currencies for a certain amount. The user does not need to have
        enough offchain balance for both the sending and receiving currencies as
        the channels will be automatically set up. The user will be charged for the
        onchain fees needed to set up the channels. The swap operation will be
        performed after the channels are ready.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelSimpleSwap(self, request, context):
        """This method is used to cancel an ongoing simple swap operation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeSimpleSwaps(self, request, context):
        """This method is used to subscribe to the updates of simple swaps.
        The user will receive updates about the swap operation, including the
        status of the channels being set up, the order matching, and the final
        result of the swap.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateSimpleSwappableAmounts(self, request, context):
        """Estimate the smallest and largest amounts that can be simple-swapped
        between two currencies given the user's wallet balances, the current
        orderbook liquidity, and the LP's leaseable capacity.

        The minimum is the smallest sending amount that still clears the
        matcher floor and all per-operation fees (channel deposit/lease/
        withdrawal/token approval). The maximum is bounded by the user's
        available balances (off-chain + on-chain) and the LP's leaseable
        liquidity.

        When no orderbook liquidity exists for the pair, returns an empty
        `amounts` field. When the pair has liquidity but no simple-swap is
        currently feasible (e.g. balance below the fee minimum), returns
        `amounts` with all four fields set to `0`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SwapServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EstimateSwap': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateSwap,
                    request_deserializer=swap__pb2.EstimateSwapRequest.FromString,
                    response_serializer=swap__pb2.EstimateSwapResponse.SerializeToString,
            ),
            'Swap': grpc.unary_unary_rpc_method_handler(
                    servicer.Swap,
                    request_deserializer=swap__pb2.SwapRequest.FromString,
                    response_serializer=swap__pb2.SwapResponse.SerializeToString,
            ),
            'EstimateSimpleSwap': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateSimpleSwap,
                    request_deserializer=swap__pb2.EstimateSimpleSwapRequest.FromString,
                    response_serializer=swap__pb2.EstimateSimpleSwapResponse.SerializeToString,
            ),
            'SimpleSwap': grpc.unary_unary_rpc_method_handler(
                    servicer.SimpleSwap,
                    request_deserializer=swap__pb2.SimpleSwapRequest.FromString,
                    response_serializer=swap__pb2.SimpleSwapResponse.SerializeToString,
            ),
            'CancelSimpleSwap': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelSimpleSwap,
                    request_deserializer=swap__pb2.CancelSimpleSwapRequest.FromString,
                    response_serializer=swap__pb2.CancelSimpleSwapResponse.SerializeToString,
            ),
            'SubscribeSimpleSwaps': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeSimpleSwaps,
                    request_deserializer=swap__pb2.SubscribeSimpleSwapsRequest.FromString,
                    response_serializer=swap__pb2.SimpleSwapUpdate.SerializeToString,
            ),
            'EstimateSimpleSwappableAmounts': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateSimpleSwappableAmounts,
                    request_deserializer=swap__pb2.EstimateSimpleSwappableAmountsRequest.FromString,
                    response_serializer=swap__pb2.EstimateSimpleSwappableAmountsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hydra_app.SwapService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hydra_app.SwapService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SwapService(object):
    """Swap service for performing cross-currency swap operations.

    Provides both basic swaps (requiring pre-existing off-chain balances)
    and "simple swaps" that automatically set up the necessary channels
    via deposits and/or leases before executing the swap.

    JSON-RPC namespace: `swap`
    """

    @staticmethod
    def EstimateSwap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.SwapService/EstimateSwap',
            swap__pb2.EstimateSwapRequest.SerializeToString,
            swap__pb2.EstimateSwapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Swap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.SwapService/Swap',
            swap__pb2.SwapRequest.SerializeToString,
            swap__pb2.SwapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateSimpleSwap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.SwapService/EstimateSimpleSwap',
            swap__pb2.EstimateSimpleSwapRequest.SerializeToString,
            swap__pb2.EstimateSimpleSwapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SimpleSwap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.SwapService/SimpleSwap',
            swap__pb2.SimpleSwapRequest.SerializeToString,
            swap__pb2.SimpleSwapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelSimpleSwap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.SwapService/CancelSimpleSwap',
            swap__pb2.CancelSimpleSwapRequest.SerializeToString,
            swap__pb2.CancelSimpleSwapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeSimpleSwaps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hydra_app.SwapService/SubscribeSimpleSwaps',
            swap__pb2.SubscribeSimpleSwapsRequest.SerializeToString,
            swap__pb2.SimpleSwapUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateSimpleSwappableAmounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.SwapService/EstimateSimpleSwappableAmounts',
            swap__pb2.EstimateSimpleSwappableAmountsRequest.SerializeToString,
            swap__pb2.EstimateSimpleSwappableAmountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
