# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lib.hydra_pb import watch_only_node_pb2 as watch__only__node__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in watch_only_node_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WatchOnlyNodeServiceStub(object):
    """Watch-only node query service.

    Provides read-only methods to query the off-chain node state including
    node identity, channels, and payment history. These methods do not require
    signing capabilities and can be used for monitoring and display purposes.

    JSON-RPC namespace: `watchOnlyNode`
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNodeId = channel.unary_unary(
                '/hydra_app.WatchOnlyNodeService/GetNodeId',
                request_serializer=watch__only__node__pb2.GetNodeIdRequest.SerializeToString,
                response_deserializer=watch__only__node__pb2.GetNodeIdResponse.FromString,
                _registered_method=True)
        self.GetChannels = channel.unary_unary(
                '/hydra_app.WatchOnlyNodeService/GetChannels',
                request_serializer=watch__only__node__pb2.GetChannelsRequest.SerializeToString,
                response_deserializer=watch__only__node__pb2.GetChannelsResponse.FromString,
                _registered_method=True)
        self.GetChannelsWithCounterparty = channel.unary_unary(
                '/hydra_app.WatchOnlyNodeService/GetChannelsWithCounterparty',
                request_serializer=watch__only__node__pb2.GetChannelsWithCounterpartyRequest.SerializeToString,
                response_deserializer=watch__only__node__pb2.GetChannelsWithCounterpartyResponse.FromString,
                _registered_method=True)
        self.GetChannel = channel.unary_unary(
                '/hydra_app.WatchOnlyNodeService/GetChannel',
                request_serializer=watch__only__node__pb2.GetChannelRequest.SerializeToString,
                response_deserializer=watch__only__node__pb2.GetChannelResponse.FromString,
                _registered_method=True)
        self.GetPayments = channel.unary_unary(
                '/hydra_app.WatchOnlyNodeService/GetPayments',
                request_serializer=watch__only__node__pb2.GetPaymentsRequest.SerializeToString,
                response_deserializer=watch__only__node__pb2.GetPaymentsResponse.FromString,
                _registered_method=True)
        self.GetPendingPayments = channel.unary_unary(
                '/hydra_app.WatchOnlyNodeService/GetPendingPayments',
                request_serializer=watch__only__node__pb2.GetPendingPaymentsRequest.SerializeToString,
                response_deserializer=watch__only__node__pb2.GetPendingPaymentsResponse.FromString,
                _registered_method=True)
        self.GetPaymentsByHash = channel.unary_unary(
                '/hydra_app.WatchOnlyNodeService/GetPaymentsByHash',
                request_serializer=watch__only__node__pb2.GetPaymentsByHashRequest.SerializeToString,
                response_deserializer=watch__only__node__pb2.GetPaymentsByHashResponse.FromString,
                _registered_method=True)
        self.GetPayment = channel.unary_unary(
                '/hydra_app.WatchOnlyNodeService/GetPayment',
                request_serializer=watch__only__node__pb2.GetPaymentRequest.SerializeToString,
                response_deserializer=watch__only__node__pb2.GetPaymentResponse.FromString,
                _registered_method=True)


class WatchOnlyNodeServiceServicer(object):
    """Watch-only node query service.

    Provides read-only methods to query the off-chain node state including
    node identity, channels, and payment history. These methods do not require
    signing capabilities and can be used for monitoring and display purposes.

    JSON-RPC namespace: `watchOnlyNode`
    """

    def GetNodeId(self, request, context):
        """Returns the node's public key (node ID) for the specified network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChannels(self, request, context):
        """Returns all channels associated with the node on the specified network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChannelsWithCounterparty(self, request, context):
        """Returns all channels with a specific counterparty on the specified
        network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChannel(self, request, context):
        """Returns the details of a specific channel by its ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPayments(self, request, context):
        """Returns all off-chain payments associated with the node on the specified
        network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingPayments(self, request, context):
        """Returns all pending (in-flight) off-chain payments on the specified
        network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPaymentsByHash(self, request, context):
        """Returns all payments matching a specific payment hash on the specified
        network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPayment(self, request, context):
        """Returns the details of a specific payment by its unique ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WatchOnlyNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNodeId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeId,
                    request_deserializer=watch__only__node__pb2.GetNodeIdRequest.FromString,
                    response_serializer=watch__only__node__pb2.GetNodeIdResponse.SerializeToString,
            ),
            'GetChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChannels,
                    request_deserializer=watch__only__node__pb2.GetChannelsRequest.FromString,
                    response_serializer=watch__only__node__pb2.GetChannelsResponse.SerializeToString,
            ),
            'GetChannelsWithCounterparty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChannelsWithCounterparty,
                    request_deserializer=watch__only__node__pb2.GetChannelsWithCounterpartyRequest.FromString,
                    response_serializer=watch__only__node__pb2.GetChannelsWithCounterpartyResponse.SerializeToString,
            ),
            'GetChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChannel,
                    request_deserializer=watch__only__node__pb2.GetChannelRequest.FromString,
                    response_serializer=watch__only__node__pb2.GetChannelResponse.SerializeToString,
            ),
            'GetPayments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPayments,
                    request_deserializer=watch__only__node__pb2.GetPaymentsRequest.FromString,
                    response_serializer=watch__only__node__pb2.GetPaymentsResponse.SerializeToString,
            ),
            'GetPendingPayments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingPayments,
                    request_deserializer=watch__only__node__pb2.GetPendingPaymentsRequest.FromString,
                    response_serializer=watch__only__node__pb2.GetPendingPaymentsResponse.SerializeToString,
            ),
            'GetPaymentsByHash': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPaymentsByHash,
                    request_deserializer=watch__only__node__pb2.GetPaymentsByHashRequest.FromString,
                    response_serializer=watch__only__node__pb2.GetPaymentsByHashResponse.SerializeToString,
            ),
            'GetPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPayment,
                    request_deserializer=watch__only__node__pb2.GetPaymentRequest.FromString,
                    response_serializer=watch__only__node__pb2.GetPaymentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hydra_app.WatchOnlyNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hydra_app.WatchOnlyNodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WatchOnlyNodeService(object):
    """Watch-only node query service.

    Provides read-only methods to query the off-chain node state including
    node identity, channels, and payment history. These methods do not require
    signing capabilities and can be used for monitoring and display purposes.

    JSON-RPC namespace: `watchOnlyNode`
    """

    @staticmethod
    def GetNodeId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.WatchOnlyNodeService/GetNodeId',
            watch__only__node__pb2.GetNodeIdRequest.SerializeToString,
            watch__only__node__pb2.GetNodeIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.WatchOnlyNodeService/GetChannels',
            watch__only__node__pb2.GetChannelsRequest.SerializeToString,
            watch__only__node__pb2.GetChannelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChannelsWithCounterparty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.WatchOnlyNodeService/GetChannelsWithCounterparty',
            watch__only__node__pb2.GetChannelsWithCounterpartyRequest.SerializeToString,
            watch__only__node__pb2.GetChannelsWithCounterpartyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.WatchOnlyNodeService/GetChannel',
            watch__only__node__pb2.GetChannelRequest.SerializeToString,
            watch__only__node__pb2.GetChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPayments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.WatchOnlyNodeService/GetPayments',
            watch__only__node__pb2.GetPaymentsRequest.SerializeToString,
            watch__only__node__pb2.GetPaymentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingPayments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.WatchOnlyNodeService/GetPendingPayments',
            watch__only__node__pb2.GetPendingPaymentsRequest.SerializeToString,
            watch__only__node__pb2.GetPendingPaymentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPaymentsByHash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.WatchOnlyNodeService/GetPaymentsByHash',
            watch__only__node__pb2.GetPaymentsByHashRequest.SerializeToString,
            watch__only__node__pb2.GetPaymentsByHashResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra_app.WatchOnlyNodeService/GetPayment',
            watch__only__node__pb2.GetPaymentRequest.SerializeToString,
            watch__only__node__pb2.GetPaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
