"""
Dry run of easy mode: planner, config generation, channel requests, lease
autopilot, Telegram control. No node, no funds, no network.

    python3 backtest/easy_dryrun.py        # from the repo root, project venv
"""
import os, re, sys, json, tempfile, time, types, logging
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
os.chdir(ROOT)
logging.basicConfig(level=logging.ERROR)
for k in ("ALERTS_TELEGRAM_BOT_TOKEN", "ALERTS_TELEGRAM_CHAT_ID"):
    os.environ[k] = ""

import yaml
from lib import planner as PL
from lib import easy_ops as E
from strategies.market_maker import MarketMakerStrategy

RESULTS = []
def check(label, ok, detail=""):
    RESULTS.append(bool(ok))
    print(f"  [{'PASS' if ok else 'FAIL'}] {label}" + (f"  ({detail})" if detail else ""))

PX = {"BTC": 83500.0, "ETH": 2690.0}
own_usd = lambda p: sum(v["own_usd"] for v in p.assets.values())

print("\n1. planner")
for budget in (500, 2000, 10000):
    for preset in PL.PRESETS:
        p = PL.plan(budget, preset, prices=PX)
        ok = True
        for e in p.entries:
            try:
                MarketMakerStrategy.build_config(e["name"], e)
            except ValueError:
                ok = False
        total = own_usd(p)
        check(f"${budget} {preset:<12}: {len(p.entries)} markets, configs valid, needs ${total:,.0f} (fits)",
              ok and total <= budget + 1 and p.entries, f"{total:,.0f}")
p = PL.plan(2000, "balanced", prices=PX)
ub = next(e for e in p.entries if e["pair"] == "BTC/USDC.arb")["params"]
check("BTC/USDC: first quote 0.35%, position capped well below a full side (the bot carries the price risk)",
      ub["half_spread_pct"] == 0.35 and ub["max_position"] < 0.5 * ub["level_size"] * ub["levels"]
      and set(ub) <= {"levels", "level_size", "bid_size", "ask_size", "half_spread_pct", "level_step_pct", "max_position",
                      "skew_pct_at_max", "size_skew", "reprice_threshold_pct", "fail_pause", "maker_fee_pct",
                      "taker_fee_pct", "state_dir"}, f"{ub}")
uu = next(e for e in p.entries if e["pair"] == "USDC.arb/USDC.eth")["params"]
check("USDC/USDC: fixed fair 1.0, tight spread, the only market that takes mispriced orders",
      uu["fair_value"] == 1.0 and uu["half_spread_pct"] <= 0.15 and "take_edge_pct" in uu and "take_edge_pct" not in ub)
check("every asset gets inbound >= what the other side can sell into it",
      all(v["inbound"] >= p.capacity[a]["recv"] for a, v in p.assets.items()))
small = PL.plan(400, "balanced", prices=PX)
check("small budget: dust markets dropped with a plain warning", len(small.entries) < 4 and
      any("too little to quote" in w for w in small.warnings), f"{[e['pair'] for e in small.entries]}")
tiny = PL.plan(150, "balanced", prices=PX)
check("tiny budget: nothing to quote, says why", not tiny.entries and any("$300" in w for w in tiny.warnings))
try:
    PL.plan(1000, "yolo", prices=PX); ok = False
except ValueError:
    ok = True
check("unknown preset refused", ok)
one = PL.plan(1000, "balanced", markets=["BTC/USDC.arb"], prices=PX)
check("one market: the whole budget goes there", [e["pair"] for e in one.entries] == ["BTC/USDC.arb"] and
      one.entries[0]["params"]["level_size"] > ub["level_size"])
check("lease cost estimate ~0.002%/h of the inbound", abs(p.lease_cost_week_usd -
      sum(v["inbound_usd"] for v in p.assets.values()) * 0.00002 * 168) < 0.05, f"${p.lease_cost_week_usd}")
check("describe() is plain words", "deposit" in PL.describe(p) and "lease inbound" in PL.describe(p))

print("\n2. config files")
tmp = tempfile.mkdtemp()
cfg_path = os.path.join(tmp, "bot_config.yaml")
open(cfg_path, "w").write("old: true\n")
backup = E.write_bot_config(p, cfg_path)
doc = yaml.safe_load(open(cfg_path))
check("bot_config written, old one kept as a backup", backup and os.path.exists(backup) and
      len(doc["strategies"]) == len(p.entries) and "Generated by" in open(cfg_path).read())
check("the written config loads in the bot (all market makers valid)",
      all(MarketMakerStrategy.build_config(e["name"], e) for e in doc["strategies"]))
link = os.path.join(tmp, "link.yaml"); real = os.path.join(tmp, "data.yaml")
open(real, "w").write("x: 1\n"); os.symlink(real, link)
E.write_bot_config(p, link)
check("through a symlink (container data volume): the real file is replaced, the link stays",
      os.path.islink(link) and "strategies" in open(real).read())
ops_path = os.path.join(tmp, "ops.yaml")
E.write_ops_config(p, ops_path, lease_autorenew=True, max_fee_usd=12)
ops = yaml.safe_load(open(ops_path))
check("ops.yaml: capacity needs from the plan + lease autopilot on", ops["capacity_need"] == p.capacity and
      ops["lease_autorenew"]["enabled"] and ops["lease_autorenew"]["max_fee_usd"] == 12)
env = os.path.join(tmp, ".env")
open(env, "w").write("A=1\nAPI_KEY=old\n")
E.set_env(env, {"API_KEY": "new", "B": "2"})
check(".env: keys replaced, others kept, file 0600", open(env).read().splitlines() == ["A=1", "API_KEY=new", "B=2"]
      and oct(os.stat(env).st_mode & 0o777) == "0o600")

print("\n3. channel requests (one OpenOrDeposit per chain)")
reqs = E.channel_requests(p, PX, cap={}, hub={"bitcoin": "03ab", "ethereum": "0xhub", "arbitrum": "0xhub"})
chains = {r["chain"]: r for r in reqs}
check("one request per chain; ETH and USDC.eth share the ethereum channel",
      set(chains) == {"bitcoin", "ethereum", "arbitrum"} and set(chains["ethereum"]["assets"]) == {"ETH", "USDC.eth"})
check("deposit = the plan's own funds, inbound = the plan's lease",
      abs(chains["bitcoin"]["assets"]["BTC"]["own"] - p.assets["BTC"]["own"]) < 1e-12 and
      abs(chains["bitcoin"]["assets"]["BTC"]["inbound"] - p.assets["BTC"]["inbound"]) < 1e-12)
cap = {"BTC": {"send": p.assets["BTC"]["own"], "recv": p.assets["BTC"]["inbound"]},
       "USDC.arb": {"send": 100.0, "recv": 0.0}}
reqs2 = {r["chain"]: r for r in E.channel_requests(p, PX, cap)}
check("existing capacity is subtracted: a funded chain is skipped, a partial one topped up",
      "bitcoin" not in reqs2 and abs(reqs2["arbitrum"]["assets"]["USDC.arb"]["own"] - (p.assets["USDC.arb"]["own"] - 100)) < 1e-9)
tinyplan = PL.plan(600, "balanced", markets=["BTC/USDC.arb"], prices=PX)
tcap = {"USDC.arb": {"send": tinyplan.assets["USDC.arb"]["own"], "recv": tinyplan.assets["USDC.arb"]["inbound"] - 2}}
r3 = {r["chain"]: r for r in E.channel_requests(tinyplan, PX, tcap)}
check("an inbound top-up under $10 is raised to the $10 lease minimum",
      r3["arbitrum"]["assets"]["USDC.arb"]["inbound"] >= 10.0, f"{r3['arbitrum']['assets']}")
req = E._liquidity_request(chains["ethereum"])
liq = req.operation.open_or_deposit.asset_liquidity
check("ethereum request: USDC.eth deposited by the service (fee from it), ETH only leased; hub node left to the service",
      req.HasField("dual_fund_fee_payment") and not req.operation.open_or_deposit.HasField("target_node_pubkey") and
      float(liq[E.ASSET_IDS["USDC.eth"]].client_amount.value) > 0 and float(liq[E.ASSET_IDS["ETH"]].client_amount.value) == 0
      and float(liq[E.ASSET_IDS["ETH"]].server_amount.value) > 0 and req.payment_asset_id == E.ASSET_IDS["USDC.eth"]
      and req.lease_duration_seconds == 168 * 3600)
check("native ETH goes in with our own DepositChannel afterwards",
      E.native_deposits(chains["ethereum"]) == {"ETH": chains["ethereum"]["assets"]["ETH"]["own"]})
eth_only = {"chain": "ethereum", "assets": {"ETH": {"own": 0.1, "inbound": 0.2}}, "hours": 168}
eo = E._liquidity_request(eth_only)
check("ETH-only: lease with the fee paid off-chain (no token to take it from), deposit separately",
      eo.HasField("offchain_fee_payment") and E.fee_mode(eth_only) == ("offchain", "USDC.arb") and
      float(eo.operation.open_or_deposit.asset_liquidity[E.ASSET_IDS["ETH"]].client_amount.value) == 0)
dep_only = {"chain": "ethereum", "assets": {"ETH": {"own": 0.1, "inbound": 0.0}}, "hours": 168}
check("native deposit with enough inbound: no service call at all", not E.needs_request(dep_only) and
      E.estimate_channel(dep_only) == (0.0, None))
check("arbitrum is funded first (it pays the other chains' fees)", [r["chain"] for r in reqs][0] == "arbitrum")
btc = E._liquidity_request(chains["bitcoin"])
bl = btc.operation.open_or_deposit.asset_liquidity[E.ASSET_IDS["BTC"]]
check("bitcoin (no dual funding): lease only, fee from the USDC.arb channel; our BTC is spliced in after",
      btc.HasField("offchain_fee_payment") and float(bl.client_amount.value) == 0 and float(bl.server_amount.value) > 0
      and btc.payment_asset_id == E.ASSET_IDS["USDC.arb"])
ino = E._liquidity_request({"chain": "arbitrum", "assets": {"USDC.arb": {"own": 0.0, "inbound": 100.0}}, "hours": 168})
check("nothing to deposit: fee paid off-chain (dual funding needs a deposit)", ino.HasField("offchain_fee_payment"))
check("a bitcoin top-up with enough inbound needs no service call (deposit only, fee 0)",
      E.estimate_channel({"chain": "bitcoin", "assets": {"BTC": {"own": 0.001, "inbound": 0.0}}, "hours": 168}) == (0.0, None))
check("service errors: its own message is shown", "DualFund is not supported" in E.explain_error(
      "Lease manager\n╰─▶ code: 'Client specified an invalid argument', message: \"DualFund is not supported on Bitcoin networks\"\n    ╰╴Failed to get fee quote"))
usd = PL.plan(1640, "balanced", markets=["USDC.arb/USDC.eth"], prices=PX)
ng = {r["chain"]: r for r in E.channel_requests(usd, PX, {}, gas={"arbitrum": 0.0, "ethereum": 0.0})}
sp = E._liquidity_request(ng["arbitrum"])
spl = sp.operation.open_or_deposit.asset_liquidity[E.ASSET_IDS["USDC.arb"]]
check("no gas on the chain: sponsored deposit (permit), our amount only — the hub refuses inbound in the same request",
      ng["arbitrum"]["no_gas"] and sp.HasField("sponsored_deposit_fee_payment") and
      float(spl.client_amount.value) == usd.assets["USDC.arb"]["own"] and float(spl.server_amount.value) == 0)
wg = {r["chain"]: r for r in E.channel_requests(usd, PX, {}, gas={"arbitrum": 0.001, "ethereum": 0.001})}
check("with gas: one dual-funded round (cheaper: one fee)", not wg["arbitrum"]["no_gas"] and
      E._liquidity_request(wg["arbitrum"]).HasField("dual_fund_fee_payment"))
after = {"USDC.arb": {"send": usd.assets["USDC.arb"]["own"], "recv": 0.0}}
second = {r["chain"]: r for r in E.channel_requests(usd, PX, after, gas={"arbitrum": 0.0})}["arbitrum"]
sl = E._liquidity_request(second)
check("next run after the sponsored deposit: the lease alone, fee off-chain from the USDC.arb channel",
      sl.HasField("offchain_fee_payment") and second["assets"]["USDC.arb"]["own"] == 0 and
      float(sl.operation.open_or_deposit.asset_liquidity[E.ASSET_IDS["USDC.arb"]].server_amount.value) > 0)
check("USDC-only plan asks for no ETH", not any("ETH" in w for w in usd.warnings), f"{usd.warnings}")
wallet = {"BTC": p.assets["BTC"]["own"], "ETH": 0.0}
gaps = E.funding_gaps(p, wallet, {"USDC.arb": {"send": p.assets["USDC.arb"]["own"]}})
check("funding gaps: what still has to reach the wallet", "BTC" not in gaps and "USDC.arb" not in gaps and
      abs(gaps["ETH"] - p.assets["ETH"]["own"]) < 1e-12 and "USDC.eth" in gaps)
check("allowance error parsed (approve exactly, then retry)",
      E.allowance_needed("... InsufficientAllowance: spender=0xcc4c47cf0175aa8108e78679c2586a0a6abb242a current=0")
      == ("0xcc4c47cf0175aa8108e78679c2586a0a6abb242a", 0))
raw = ("Failed to initiate channel opening\n    ├╴InsufficientAllowance: spender=0x895090d931660fbfc5f6bdedc24a87dd3d64202d "
       "current=0 needed=690740982\n    ├╴Pre-flight allowance check failed for token "
       "erc20:0xaf88d065e77c8cc2239327c5edb3a432268e5831: owner=0x3a03 current=0 needed=690740982")
check("approval request parsed from the node's real error: spender, token, deposit + fee",
      E.allowance_request(raw) == ("0x895090d931660fbfc5f6bdedc24a87dd3d64202d",
                                   "erc20:0xaf88d065e77c8cc2239327c5edb3a432268e5831", 690740982))
class FakeStub:
    def __init__(self): self.calls = 0
    def EstimateRequestChannelLiquidityFee(self, r): return types.SimpleNamespace(fee=types.SimpleNamespace(value="2.74"))
    def RequestChannelLiquidity(self, r, timeout=None):
        import grpc
        self.calls += 1
        if self.calls == 1:
            class Err(grpc.RpcError):
                def details(self): return raw
            raise Err()
        return types.SimpleNamespace(channel_id="0xchan", txid="0xtx", fee=types.SimpleNamespace(value="2.74"))
fs = FakeStub(); approvals = []
orig = (E.liquidity_stub, E.approve, E.time.sleep)
E.liquidity_stub = lambda: fs
E.approve = lambda c, chain, asset, spender, amount: approvals.append((chain, asset, spender, amount)) or "0xapprove"
E.time.sleep = lambda s: None
res = E.open_channel(None, {"chain": "arbitrum", "assets": {"USDC.arb": {"own": 688.0, "inbound": 786.0}}, "hours": 168},
                     log=lambda *a: None)
E.liquidity_stub, E.approve, E.time.sleep = orig
check("open_channel: refused for allowance -> approves needed + 0.5% (690.740982 -> 694.194686, the fee moves) -> retries -> opened",
      res["ok"] and res["channel"] == "0xchan" and approvals == [("arbitrum", "USDC.arb",
      "0x895090d931660fbfc5f6bdedc24a87dd3d64202d", "694.194686")] and fs.calls == 2, f"{res} {approvals}")
check("18-decimal amounts stay exact (a float approval of HDN came out short)",
      E.base_units_to_decimal(25104544997151929665958, 18) == "25104.544997151929665958" and
      E.base_units_to_decimal(690740982, 6) == "690.740982" and E.base_units_to_decimal(10**18, 18) == "1")
check("errors in plain words", "7 days" in E.explain_error("the extension would carry the lease 688170s past now, "
      "beyond the furthest a lease may reach (605370s past now, the maximum of 604800s)"))

usd2 = PL.plan(1910, "balanced", markets=["USDC.arb/USDC.eth"], prices=PX)
f, have, plan_usd, empty = E.funding_state(usd2, {"USDC.arb": {"send": 893.13}, "USDC.eth": {"send": 707.46}}, PX)
check("doctor: value moved between the two sides after a fill (893 / 707 vs 803 / 803) still counts as funded",
      f and not empty and abs(have - 1600.59) < 0.01, f"{have:.2f} of {plan_usd:.2f}")
f, have, plan_usd, empty = E.funding_state(usd2, {"USDC.arb": {"send": 803.0}}, PX)
check("doctor: one side empty -> not funded, named", not f and empty == ["USDC.eth"])

dl = E.daily_stats_lines({"BTC/USDC.arb": {"first": 83164.88, "last": 83422.17, "high": 0, "low": 0, "base_volume": 0.96, "quote_volume": 80197.68},
                          "ETH/BTC": {"first": 0.032011, "last": 0.032185, "high": 0, "low": 0, "base_volume": 0.84, "quote_volume": 0.026986},
                          "ETH.arb/ETH": {"first": 0, "last": 0, "high": 0, "low": 0, "base_volume": 0, "quote_volume": 0}})
check("daily stats: volume per market, BTC-quoted in USD, empty markets left out, total",
      len(dl) == 3 and "80,197.7 USDC.arb" in dl[0] and "($2,251)" in dl[1] and "~$82,449" in dl[2], f"{dl}")

print("\n4. lease autopilot")
check("extension capped so the lease ends <= 7 days out", E.lease_extension_hours(21 * 3600, 168) == 147 and
      E.lease_extension_hours(0, 168) == 168 and E.lease_extension_hours(7 * 24 * 3600, 168) == 0)
src = open("tools/ops_daemon.py").read().split("\nif __name__")[0]
g = {"__name__": "od", "__file__": os.path.abspath("tools/ops_daemon.py")}
exec(compile(src, "od", "exec"), g)
from lib.alerts import Alerter
class Liq:
    """fee: USDC.arb fee; hdn_fee: fee in HDN (None = the service refuses HDN)."""
    def __init__(self, left_h, fee, liq_h=None, hdn_fee=None):
        self.left_h, self.fee, self.liq_h, self.hdn_fee, self.extended, self.paid = left_h, fee, liq_h, hdn_fee, [], []
    def GetLeases(self, req):
        if req.network.id != "1": return types.SimpleNamespace(leases=[])
        l = g["L"].AssetChannelLease(channel_id="0x7e57c4a11e", asset_id="0x" + "0" * 40)
        l.expiry.seconds = int(time.time() + self.left_h * 3600)
        if self.liq_h is not None:
            l.liquidity_expiry.seconds = int(time.time() + self.liq_h * 3600)
        return types.SimpleNamespace(leases=[l])
    def EstimateRequestChannelLeaseExtensionFee(self, req):
        if "b0f66b" in req.payment_asset_id:
            if self.hdn_fee is None:
                import grpc
                class Err(grpc.RpcError):
                    def details(self): return "asset not accepted for payment"
                raise Err()
            return types.SimpleNamespace(fee=types.SimpleNamespace(value=str(self.hdn_fee)))
        return types.SimpleNamespace(fee=types.SimpleNamespace(value=str(self.fee)))
    def RequestChannelLeaseExtension(self, req, timeout=None):
        self.extended.append(req.lease_extension_seconds // 3600)
        self.paid.append("HDN" if "b0f66b" in req.payment_asset_id else "USDC.arb")
        self.left_h += req.lease_extension_seconds / 3600
        return types.SimpleNamespace(expiry_timestamp_seconds=int(time.time() + self.left_h * 3600))
g["hdn_usd"] = lambda: 0.0265                       # no network in the dry run
def run(left_h, fee, cfg, liq_h=None, al=None, hdn_fee=None):
    if al is None:
        al = Alerter(logging.getLogger("t"), state_path=f"{tempfile.mkdtemp()}/a.json", config_path="/nonexistent")
    sent = []; al.send = sent.append
    liq = Liq(left_h, fee, liq_h, hdn_fee)
    g["check_leases"](al, liq, cfg)
    return liq, sent, al
AUTO = {"lease_autorenew": {"enabled": True, "renew_below_hours": 24, "extend_hours": 168, "max_fee_usd": 5}}
liq, sent, al = run(20, 2.65, AUTO)
check("HDN refused -> USDC.arb: ending in 20h, fee 2.65 <= 5: extended by 148h, one 🔄 message, no ⏳ warning",
      liq.extended == [148] and len(sent) == 1 and sent[0].startswith("🔄") and not al.active, f"{liq.extended} {sent}")
liq, sent, al = run(20, 9.0, AUTO)
check("fee above the cap: not extended, one ⚠️ + the normal ⏳ warning",
      not liq.extended and any(s.startswith("⚠️") for s in sent) and any(s.startswith("⏳") for s in sent))
liq, sent, al = run(20, 2.65, AUTO, hdn_fee=100.0)
check("fees in HDN when the service takes it: 100 HDN ($2.65) <= $5, paid in HDN", liq.paid == ["HDN"] and
      "100.00 HDN" in sent[0], f"{liq.paid} {sent}")
liq, sent, al = run(20, 2.65, AUTO, hdn_fee=400.0)
check("HDN fee above the cap in USD (400 HDN = $10.60 > $5): not extended", not liq.extended and
      any("$10.60" in x for x in sent), f"{sent}")
liq, sent, al = run(60, 1.0, AUTO)
check("ending in 60h: left alone", not liq.extended and not sent)
liq, sent, al = run(20, 1.0, {})
check("autopilot off (the mainnet default): only the warning", not liq.extended and sent and sent[0].startswith("⏳"))
liq, sent, al2 = run(20, 1.0, AUTO, liq_h=24 * 30)
check("lease ends in 20h but the hub keeps its liquidity 30 days (activity): no warning, nothing paid",
      not liq.extended and not sent)
liq, sent, _ = run(20, 1.0, {})
liq2, sent2, _ = run(20, 1.0, {}, liq_h=24 * 30, al=al)
check("a warned lease the hub then keeps: ✅ 'kept by the hub'", sent2 and sent2[0].startswith("✅") and "hub" in sent2[0],
      f"{sent2}")

class CapClient:
    def __init__(self): self.send = 900.0
    def get_orderbook_balances(self):
        D = lambda x: types.SimpleNamespace(value=str(x))
        return [types.SimpleNamespace(currency=types.SimpleNamespace(network_id="42161", asset_id="erc20:0xaf88d065e77c8cc2239327c5edb3a432268e5831"),
                                      balance=types.SimpleNamespace(sending=D(self.send), in_use_sending=D(0), receiving=D(800), in_use_receiving=D(0)))]
al = Alerter(logging.getLogger("t"), state_path=f"{tempfile.mkdtemp()}/a.json", config_path="/nonexistent")
sent = []; al.send = sent.append
cc, ccfg = CapClient(), {"capacity_need": {"USDC.arb": {"send": 765, "recv": 765}}}
g["_CAP_LOW"].clear()
cc.send = 0.0; g["check_capacity"](al, cc, ccfg)                  # node starting: a chain reads 0 once
cc.send = 893.0; g["check_capacity"](al, cc, ccfg)
check("capacity 0 for one check (node starting) -> no 📉/✅ pair", not sent, f"{sent}")
cc.send = 0.0; g["check_capacity"](al, cc, ccfg); g["check_capacity"](al, cc, ccfg)
check("low at two checks in a row -> one 📉 alert", len(sent) == 1 and sent[0].startswith("📉"), f"{sent}")

# lease alerts: GetLeases leaving a live lease out once is not "ended"
class FlakyLiq(Liq):
    def __init__(self, *a, **k):
        super().__init__(*a, **k); self.hide = False
    def GetLeases(self, req):
        return types.SimpleNamespace(leases=[]) if self.hide else super().GetLeases(req)
al = Alerter(logging.getLogger("t"), state_path=f"{tempfile.mkdtemp()}/a.json", config_path="/nonexistent")
sent = []; al.send = sent.append
fl = FlakyLiq(20, 1.0)
g["_LEASE_MISSING"].clear()
g["check_leases"](al, fl, {}); fl.hide = True; g["check_leases"](al, fl, {}); fl.hide = False; g["check_leases"](al, fl, {})
check("lease missing from one GetLeases answer: no ⌛/⏳ flicker (one ⏳ only)",
      len(sent) == 1 and sent[0].startswith("⏳"), f"{sent}")
fl.hide = True; g["check_leases"](al, fl, {}); g["check_leases"](al, fl, {})
check("missing twice but its end (in 20h) not reached: still no ⌛", len(sent) == 1, f"{sent}")
key = next(iter(al.active)); al.active[key] = al.active[key].replace(
    re.search(r"ends (\w{3} \d{2} \d{2}:\d{2})", al.active[key]).group(1),
    time.strftime("%b %d %H:%M", time.gmtime(time.time() - 3600)))
g["check_leases"](al, fl, {})
check("missing again and its end passed: ⌛ has ended", len(sent) == 2 and sent[1].startswith("⌛"), f"{sent}")
check("lease end parsed from the warning text", abs(g["_lease_end"]("ends " + time.strftime("%b %d %H:%M", time.gmtime(time.time() + 7200)) + " UTC")
                                                     - (time.time() + 7200)) < 61)

# small fills summed in the digest
g["FAIRS"]["BTC/USDC.arb"] = 84000.0
items = ["💱 BTC/USDC.arb: SOLD 0.0000124 @ 84,050.15 (≈ 1.04222 USDC.arb, partial fill) — position -0.0024405 (-10%)\n"
         "💱 BTC/USDC.arb: SOLD 0.0000125 @ 84,050.15 (≈ 1.05063 USDC.arb, partial fill) — position -0.002453 (-10%)",
         "💱 ETH/BTC: BOUGHT 0.00116349 @ 0.0319728 (≈ 0.0000372 BTC, partial fill) — position +0.000927474 (+1%)",
         "💱 BTC/USDC.arb: SOLD 0.0004729 @ 84,357.18 (≈ 39.8925 USDC.arb, partial fill) — position -0.0029159 (-12%)",
         "💱 BTC/USDC.arb: SOLD 0.000013 @ 84,139.23 (≈ 1.09381 USDC.arb, partial fill) — position -0.0029289 (-12%)",
         "⏳ Lease BTC inbound (channel 0x7e57c4a2) ends Oct 02 08:00 UTC (<24h left)"]
body = g["compact_digest"](items, 5.0)
check("digest: 3 small BTC/USDC sells -> one line with total, count and last position",
      any(l.startswith("💱 BTC/USDC.arb: SOLD 0.0000379 in 3 small fills") and "-0.0029289" in l for l in body), f"{body}")
check("digest: the $40 fill and the alert keep their own lines",
      sum("39.8925" in l for l in body) == 1 and body[-1].startswith("⏳"), f"{body}")
check("digest: a single small fill (ETH/BTC, $3) stays as it is; header still counts all 5 fills",
      sum(l.startswith("💱 ETH/BTC: BOUGHT 0.00116349") for l in body) == 1
      and "💱 5 fills" in g["digest_header"](items), f"{body}")

ul = ("2026-10-06 11:00:00,1 - strategy.mm_usdc_usdc - INFO - 💱 USDC.arb/USDC.eth: buy 131 @ 0.999 (filled) — "
      "position +131 (+33% of max)")
check("fill message: 'position +131 (+33%)'", "— position +131 (+33%)" in (g["fill_messages"]([ul]) or ""))

print("\n5. Telegram control")
import importlib.util
spec = importlib.util.spec_from_file_location("tg", "tools/tg_control.py"); tg = importlib.util.module_from_spec(spec)
spec.loader.exec_module(tg)
root = tempfile.mkdtemp(); os.makedirs(os.path.join(root, "state"))
E.ROOT_BAK = E.ROOT
cfgp = os.path.join(root, "bot.yaml"); yaml.safe_dump({"strategies": p.entries}, open(cfgp, "w"))
open(os.path.join(root, "trading_bot.log"), "w").write(
    "2026-09-30 12:00:00,1 - strategy.mm_btc_usdc - INFO - 📊 BTC/USDC.arb: fair 83500.0 | 6 bids 83300.0 / 6 asks "
    "83700.0 | position -0.02 (-100%) | 75 fills, volume 0.02 | est. P&L +19.13 (trading ...) in quote units\n")
orig_status, orig_pause = E.market_status, E.set_pause
E.market_status = lambda *a, **k: orig_status(root=root)
E.set_pause = lambda on, market=None, root_=root: orig_pause(on, market, root=root)
check("/id answers any chat (needed to finish the setup)", tg.handle("/id", "-5515", allowed="") == "chat id: -5515")
check("other chats get nothing", tg.handle("/status", "999", allowed="-5515", config_path=cfgp) == "")
st = tg.handle("/status", "-5515", allowed="-5515", config_path=cfgp)
check("/status: markets from the log", "BTC/USDC.arb" in st and "6 bids / 6 asks" in st and "▶️" in st, st)
check("/pnl", "+19.13" in tg.handle("/pnl", "-5515", allowed="-5515", config_path=cfgp))
r = tg.handle("/pause mm_btc_usdc", "-5515", allowed="-5515", config_path=cfgp)
check("/pause <market>: that market's pause file", os.path.exists(os.path.join(root, "state", "pause_mm_btc_usdc"))
      and "Paused mm_btc_usdc" in r and "⏸" in tg.handle("/status", "-5515", allowed="-5515", config_path=cfgp))
check("/pause with an unknown market: lists the real ones", "Unknown market" in
      tg.handle("/pause mm_nope", "-5515", allowed="-5515", config_path=cfgp))
tg.handle("/resume", "-5515", allowed="-5515", config_path=cfgp)
check("/resume (all): every pause file gone", not [f for f in os.listdir(os.path.join(root, "state")) if f.startswith("pause")])
check("/help@botname works in groups", "/status" in tg.handle("/help@hydra_mm_bot", "-5515", allowed="-5515"))
open(os.path.join(root, "trading_bot.log"), "a").write(
    "2026-09-30 14:20:01,5 - strategy.mm_usdc_usdc - INFO - 💱 USDC.arb/USDC.eth: buy 131 @ 0.999 (filled) — position +131 (+33% of max)\n")
orig_fills = E.recent_fills
E.recent_fills = lambda n=5: orig_fills(n, root=root)
fl = tg.handle("/fills", "-5515", allowed="-5515", config_path=cfgp)
check("/fills: latest fills from the log", "bought 131.00 @ 0.999" in fl and "position +131" in fl, fl)
E.recent_fills = orig_fills
BK = {"bids": [(0.999, 131.0, True), (0.998, 50.0, False)], "asks": [(1.001, 131.0, True), (1.002, 20.0, False)]}
orig_dm, orig_book = E.dex_markets, E.book
E.dex_markets = lambda node: {"USDC.arb/USDC.eth": ("b", "q"), "BTC/USDC.arb": ("b2", "q2")}
E.book = lambda node, pair, cur=None: BK if pair == "USDC.arb/USDC.eth" else {"bids": [], "asks": []}
bk = tg.handle("/book mm_usdc_usdc", "-5515", allowed="-5515", config_path=cfgp, node=object())
check("/book <strategy>: ladder with ours ★ and the spread", "USDC.arb/USDC.eth" in bk and "bid 0.999" in bk and
      "★" in bk and "spread 0.200%" in bk and bk.index("ask 1.002") < bk.index("ask 1.001") < bk.index("bid 0.999"), bk)
check("/book with a partial name ('usdc.eth')", "📖 USDC.arb/USDC.eth" in
      tg.handle("/book usdc.eth", "-5515", allowed="-5515", config_path=cfgp, node=object()))
check("/book unknown market: lists them", "Unknown market" in
      tg.handle("/book doge", "-5515", allowed="-5515", config_path=cfgp, node=object()))
od = tg.handle("/orders", "-5515", allowed="-5515", config_path=cfgp, node=object())
check("/orders: only ours", "USDC.arb/USDC.eth: 1 bids 0.999" in od and "1 asks 1.001" in od and "BTC" not in od, od)
mk = tg.handle("/markets", "-5515", allowed="-5515", config_path=cfgp, node=object())
check("/markets: best bid/ask and our share", "USDC.arb/USDC.eth: 0.999 / 1.001" in mk and "% ours" in mk, mk)
E.dex_markets, E.book = orig_dm, orig_book
cf = tg.handle("/config", "-5515", allowed="-5515", config_path=cfgp)
check("/config: settings per market", "mm_btc_usdc" in cf and "levels" in cf and "spread" in cf, cf[:120])
check("/help lists the new commands", all(c in tg.handle("/help", "-5515", allowed="-5515")
                                          for c in ("/book", "/markets", "/orders", "/fills", "/leases", "/wallet", "/config")))
print("\n7. Telegram pairing")
tmpd = tempfile.mkdtemp()
envp = os.path.join(tmpd, ".env"); open(envp, "w").write("A=1\nALERTS_TELEGRAM_CHAT_ID=-111\n")
E.PAIR_FILE = os.path.join(tmpd, "tg_pair.json")
code = E.set_telegram("123:abc", env_path=envp)
env_now = open(envp).read()
check("hydra-mm telegram: token stored, old chat unlinked, 6-digit one-time code, .env 0600",
      "ALERTS_TELEGRAM_BOT_TOKEN=123:abc" in env_now and "CHAT_ID" not in env_now and len(code) == 6 and
      code.isdigit() and oct(os.stat(envp).st_mode & 0o777) == "0o600")
check("wrong code: refused (and says why when nothing is paired yet)",
      "wrong or expired" in tg.handle("/start 000000", "-777", allowed="", env_path=envp) and "CHAT_ID" not in open(envp).read())
r = tg.handle(f"/start@hydra_easy_bot {code}", "-777", allowed="", env_path=envp)
check("/start <code>: that chat is paired (saved to .env), code used up", r.startswith("✅ Paired") and
      "ALERTS_TELEGRAM_CHAT_ID=-777" in open(envp).read() and E.pairing_code() is None, r[:40])
check("the code works once", "wrong or expired" in tg.handle(f"/start {code}", "-888", allowed="", env_path=envp))
check("a stranger's /start in a paired setup gets no answer", tg.handle("/start 123456", "-888", allowed="-777",
                                                                         env_path=envp) == "")
json.dump({"code": "424242", "expires": time.time() - 1}, open(E.PAIR_FILE, "w"))
check("an expired code is refused", E.pairing_code() is None)
E.PAIR_FILE = os.path.join("state", "tg_pair.json")
E.market_status, E.set_pause = orig_status, orig_pause

print("\n6. daemon mode stops cleanly on SIGTERM (docker stop)")
import asyncio, signal as SIG
import trading_bot_cli as TB
from strategies.base.base_strategy import StrategyManager
async def daemon_sigterm():
    bot = TB.TradingBotCLI.__new__(TB.TradingBotCLI)
    bot.logger = logging.getLogger("cli"); bot.config = TB.BotConfig(strategies=[])
    bot.strategy_manager = StrategyManager(); bot.exchanges, bot.order_trackers = {}, {}
    bot.exchange_factory = None
    bot._strategy_entries, bot._removed, bot._reload_lock, bot._reload_task = {}, {}, None, None
    bot._closing, bot._shutdown_task, bot.config_path = False, None, None
    done = []
    async def cancel_all():
        await asyncio.sleep(0.2)          # cancelling takes a moment on the real node
        done.append("cancelled")
    bot._cancel_all_orders = cancel_all
    bot.start_reload_watch = lambda: None
    task = asyncio.ensure_future(bot.start_daemon_mode())
    await asyncio.sleep(0.3)
    os.kill(os.getpid(), SIG.SIGTERM)
    await asyncio.wait_for(task, 5)
    return done
done = asyncio.run(daemon_sigterm())
check("SIGTERM: every order cancelled before the daemon returns (no orders left resting)", done == ["cancelled"], f"{done}")

passed = sum(RESULTS)
print(f"\n{passed}/{len(RESULTS)} checks passed")
sys.exit(0 if passed == len(RESULTS) else 1)
